%% main_WP_PFC_design.m
% Entry point for the PFC (Poloidal Field Coils) winding-pack (WP)
% design-point solver.
%
% Unlike main_WP_TF_design.m and main_WP_CS_design.m (one machine input
% file per run), this driver scans all 6 PF coils (PF1..PF6) and sweeps
% the winding-pack height WP_h in one run, mirroring the legacy
% PF_opt_VNS.m structure exactly (29/09/2026 decision, see manuale PFC).
%
% Pipeline:
%   1. Ask for (and let you review) the machine parameter Excel file, the
%      combined CS+PFC+plasma geometry/Ampere-turns file, and the
%      per-scenario axial-force file.
%   2. Read them into a parameter struct + geometry/force tables (io/*.m)
%      and compute the single-turn mutual/self inductance matrix of every
%      conductor (physics/compute_coupling_matrix.m - this replaces the
%      legacy's separate Poloidal_field.m + L_matrix_monoturn.xlsx round
%      trip: the coupling matrix is now computed directly here).
%   3. For each PF coil and each WP_h in the sweep, derive the turns/
%      layers/Iop search space (search/generate_combinations.m) and scan
%      every combination, keeping every design point that satisfies the
%      Ampere-turns target, the geometric checks and the ring Tresca
%      stress checks (search/scan_wp_designs.m).
%   4. Save one results table per PF coil (across its whole WP_h sweep),
%      then optionally let you browse it and choose a design point to
%      plot and save (postprocess/*.m).
%
% This is a direct port of PF_opt_VNS.m into a TF/CS-style modular
% pipeline (see the manuale PFC artifact for the full analysis and the
% "decisioni aperte" this port carries forward unresolved). It has not
% been run in MATLAB in this environment - validate a few known design
% points against PF_opt_VNS.m before trusting it for new designs.
%
% To design a different machine, do NOT edit this file: copy
% input/WP_PFC_input_template.xlsx to a new file, edit its parameters,
% and point this script at it (together with that machine's own geometry
% and axial-force files) when asked.

clearvars; close all; clc

this_dir = fileparts(mfilename('fullpath'));
addpath(genpath(this_dir));
addpath(fileparts(this_dir)); % MADE-2.0/matlab/: shared xbr.m, xbz.m, xlm.m, heat_balance_cicc_ode.m (used by TF/CS too)

default_input = fullfile(this_dir, 'input', 'WP_PFC_input_template.xlsx');

%% 1. Select and review the machine parameter file
fprintf('Machine parameter file [%s]:\n', default_input);
input_answer = strtrim(input('Press Enter to use it, or type another path: ', 's'));
if isempty(input_answer)
    input_file = default_input;
else
    input_file = input_answer;
end

fprintf(['\nBEFORE RUNNING: open %s and review every parameter - ' ...
    'this run will use exactly what is saved in that file.\n'], input_file);
proceed = strtrim(input('Type "y" to confirm and run the solver: ', 's'));
if ~strcmpi(proceed, 'y')
    fprintf('Aborted: input not confirmed.\n');
    return
end

%% 1b. Select the combined CS+PFC+plasma geometry/Ampere-turns file
fprintf('\nCombined CS+PFC+plasma geometry & Ampere-turns file (e.g. Baseline_VNS_07_2026_V3_CREATE.xlsx):\n');
geometry_file = strtrim(input('Path: ', 's'));
if isempty(geometry_file) || ~isfile(geometry_file)
    error('main_WP_PFC_design:geometry_file_required', ...
        'A valid geometry file is required (see io/read_coil_geometry.m).');
end

%% 1c. Select the per-scenario axial-force file
fprintf('\nPer-scenario axial-force file (e.g. FZ_PF.xlsx):\n');
force_file = strtrim(input('Path: ', 's'));
if isempty(force_file) || ~isfile(force_file)
    error('main_WP_PFC_design:force_file_required', ...
        'A valid axial-force file is required (see io/read_axial_force.m).');
end

[~, tag] = fileparts(input_file); % used to tag every output file from this run

%% 2. Read input and compute the coupling matrix
p = read_machine_input(input_file);
g = compute_operating_params(p);
geom = read_coil_geometry(geometry_file);
FZ_max = read_axial_force(force_file);
L_matrix = compute_coupling_matrix(geom);

%% 3. Scan every PF coil (PF1..PF6) across the WP_h sweep
n_pf_coils = 6;
all_results = cell(1, n_pf_coils);

for n_PF_idx = 1:n_pf_coils
    row = p.cs_modules + n_PF_idx;
    L_factor = sum(L_matrix(:, row))/L_matrix(row, row);
    R_center = geom.R(row);
    MAt_target = geom.MAt(row);
    FZ = FZ_max(row);

    fprintf('\nScanning PF%d (row %d, R=%.3f m, MAt target=%.3g A-turns)...\n', ...
        n_PF_idx, row, R_center, MAt_target);

    DATA_coil = table();
    for WP_h = p.WP_h_min:p.WP_h_step:p.WP_h_max
        env = generate_combinations(p, g, WP_h);
        DATA_h = scan_wp_designs(p, g, env, WP_h, R_center, MAt_target, FZ, L_factor, n_PF_idx);
        DATA_coil = [DATA_coil; DATA_h]; %#ok<AGROW>
    end
    all_results{n_PF_idx} = DATA_coil;

    if height(DATA_coil) == 0
        warning('main_WP_PFC_design:no_feasible_design', ...
            ['No feasible design point found for PF%d across WP_h = %.3g:%.3g:%.3g m.\n' ...
             'Widen the Numerical settings (Iop_min/max, min/max_size_CICC, min/max_B, ...) ' ...
             'or the WP_h range, or review the machine geometry.'], ...
            n_PF_idx, p.WP_h_min, p.WP_h_step, p.WP_h_max);
        continue
    end

    results_file = sprintf('%s_PF%d_results_%s.xlsx', tag, n_PF_idx, string(datetime('now', 'Format', 'yyyyMMdd_HHmmss')));
    writetable(DATA_coil, results_file);
    fprintf('%d feasible design point(s) for PF%d saved to %s\n', height(DATA_coil), n_PF_idx, results_file);
end

%% 4. Browse and pick a design point per coil, on request
for n_PF_idx = 1:n_pf_coils
    DATA_coil = all_results{n_PF_idx};
    if height(DATA_coil) == 0
        continue
    end
    proceed = strtrim(input(sprintf('\nBrowse PF%d design points now? [y/N]: ', n_PF_idx), 's'));
    if ~strcmpi(proceed, 'y')
        continue
    end
    sel_idx = browse_solutions(DATA_coil);
    plot_solution(DATA_coil, sel_idx, tag);
end
