function B = biot_savart_segments(P, S1, S2, I, opts)
%BIOT_SAVART_SEGMENTS Exact magnetic field of a set of straight current segments.
%
%   B = BIOT_SAVART_SEGMENTS(P, S1, S2, I) returns the magnetic field [T]
%   at the evaluation points P (Np x 3) generated by Ns straight filament
%   segments, each carrying current I(k) [A] from S1(k,:) to S2(k,:) [m]
%   (S1, S2: Ns x 3), using the closed-form Biot-Savart integral of a
%   finite straight segment (Hanson & Hirshman 2002, "Compact expressions
%   for the Biot-Savart fields of a filamentary segment"):
%
%       a = S1 - P,  b = S2 - P            (point -> segment ends)
%       B = mu0*I/(4*pi) * (|a|+|b|) / (|a|*|b|*(|a|*|b| + a.b)) * (a x b)
%
%   This is robust everywhere except when P lies on the infinite line
%   through the segment (a x b = 0): there the contribution is taken as
%   zero (no field point of this model ever sits on a real conductor).
%
%   I can be a scalar (same current on every segment) or an Ns x 1 vector.
%
%   opts.chunk (default 20000) caps the number of segments processed at
%   once per evaluation-point block, to bound memory (Np x chunk temporary
%   arrays); evaluation points are processed one at a time in a loop, which
%   keeps memory to Np1 x chunk instead of Np x Ns.
%
%   B = BIOT_SAVART_SEGMENTS(P, S1, S2, I, opts) with opts.chunk overrides
%   the default.

if nargin < 5, opts = struct(); end
if ~isfield(opts, 'chunk') || isempty(opts.chunk), opts.chunk = 20000; end

Mu_0 = 4e-7*pi;
Ns = size(S1, 1);
I = I(:);
if isscalar(I), I = I*ones(Ns, 1); end
Np = size(P, 1);
B = zeros(Np, 3);
chunk = opts.chunk;

for s0 = 1:chunk:Ns
    s1 = min(s0 + chunk - 1, Ns);
    A1 = S1(s0:s1, :); A2 = S2(s0:s1, :); Ic = I(s0:s1)';   % 1 x nb
    const = Mu_0/(4*pi) * Ic;                               % 1 x nb
    for k = 1:Np
        ax = A1(:,1)' - P(k,1); ay = A1(:,2)' - P(k,2); az = A1(:,3)' - P(k,3);
        bx = A2(:,1)' - P(k,1); by = A2(:,2)' - P(k,2); bz = A2(:,3)' - P(k,3);
        na = sqrt(ax.^2 + ay.^2 + az.^2);
        nb = sqrt(bx.^2 + by.^2 + bz.^2);
        cx = ay.*bz - az.*by; cy = az.*bx - ax.*bz; cz = ax.*by - ay.*bx;
        nc2 = cx.^2 + cy.^2 + cz.^2;
        adotb = ax.*bx + ay.*by + az.*bz;
        denom = na.*nb.*(na.*nb + adotb);
        ok = nc2 > 0 & denom > 0;                          % skip points on the segment's line
        f = zeros(size(denom)); f(ok) = const(ok).*(na(ok) + nb(ok))./denom(ok);
        B(k,1) = B(k,1) + sum(f.*cx);
        B(k,2) = B(k,2) + sum(f.*cy);
        B(k,3) = B(k,3) + sum(f.*cz);
    end
end
end
