!=======================================================================
! TF_buff.f - Buffer insulation between the WP and the ground insulation (BUFF).
! Not called by the current STR_MODEL.f.
!=======================================================================
/PREP7
LSEL,,LCCAT
LDELE,ALL
ALLSEL,ALL,ALL
NUMCMP,LINE
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!! BUFFER INSULATION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THAT_MAT = JCK_MAT
THIS_MAT = BUFF_MAT
THIS_ET = BUFF_ET
THIS_REAL = BUFF_MAT
ELM_SZ = (BUFF)/2

!!
!! TOP
!!

CSYS,REF_CS
KSEL,,LOC,Y,Ymax+GIT
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF,YREF+BUFF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,BUFF_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		ASEL,NONE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP
		ADRAG,ALL,,,,,,BUFF_EXT_LN
		AATT,THIS_MAT,,THIS_ET,TOP_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
		
!!
!! LEFT
!!

CSYS,REF_CS
KSEL,,LOC,X,Xmin-GIT!-WPW_HIGHF/2-GIT
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF-BUFF,YREF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,BUFF_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		ASEL,NONE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP
		ADRAG,ALL,,,,,,BUFF_EXT_LN
		AATT,THIS_MAT,,THIS_ET,LFT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
		
!!
!! RIGHT
!!

CSYS,REF_CS
KSEL,,LOC,X,Xmax+GIT!WPW_HIGHF/2+GIT
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF+BUFF,YREF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,BUFF_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		ASEL,NONE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP
		ADRAG,ALL,,,,,,BUFF_EXT_LN
		AATT,THIS_MAT,,THIS_ET,RGT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
		
!!
!! BOTT
!!

CSYS,REF_CS
KSEL,,LOC,Y,Ymin-GIT!WP_INTR+BUFF
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF,YREF-BUFF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,BUFF_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		ASEL,NONE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP
		ADRAG,ALL,,,,,,BUFF_EXT_LN
		AATT,THIS_MAT,,THIS_ET,BOT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL	
		
*IF,NL_LOWF,NE,0,THEN	
!!
!! LEFT CORNER
!!
	
i = GRADES-1
k = 1

CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
ASEL,S,MAT,,STEEL_FIL_MAT
ASEL,R,LOC,X,-HJW(i,k)-ICIT,HJW(i,k)+ICIT
ALLSEL,BELOW,AREA
*GET,X1,KP,,MNLOC,X
*GET,Y1,KP,,MNLOC,Y

KSEL,ALL
KSEL,S,KP,,KP(X1-GIT,Y1+RAD1,0)
*GET,KP1,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1+RAD1,Y1-GIT,0)
*GET,KP2,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1+RAD1,Y1+RAD1,0)
*GET,KP3,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1-GIT-BUFF,Y1+RAD1,0)
*GET,KP4,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1+RAD1,Y1-GIT-BUFF,0)
*GET,KP5,KP,,NUM,MAX

LSEL,S,LOC,Y,Y1+RAD1
LSEL,R,LOC,X,X1-GIT-BUFF,X1-GIT
CM,LN1,LINE

LSEL,S,LOC,Y,Y1-GIT-BUFF,Y1-GIT
LSEL,R,LOC,X,X1+RAD1
CM,LN2,LINE

LSEL,S,RADIUS,,RAD1+GIT
LSEL,R,LOC,X,X1-GIT,X1+RAD1
CM,LN3,LINE

LSEL,NONE
KSEL,ALL
LARC,KP4,KP5,KP3,RAD1+GIT+BUFF
CMSEL,A,LN1,LINE
CMSEL,A,LN2,LINE
CMSEL,A,LN3,LINE
KSLL,,1
NSLL,,1
NUMMEG,NODE
NUMMRG,KP
ASEL,NONE
AL,ALL
AATT,THIS_MAT,,THIS_ET,BOT_LFT_CS
MSHKEY,1
MSHAPE,0
AMESH,ALL
			
!!
!! RIGHT CORNER
!!

i = GRADES-1
k = NT_HIGHF

CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
ASEL,S,MAT,,STEEL_FIL_MAT
ASEL,R,LOC,X,-HJW(i,k)-ICIT,HJW(i,k)+ICIT
ALLSEL,BELOW,AREA
*GET,X1,KP,,MXLOC,X
*GET,Y1,KP,,MNLOC,Y

KSEL,ALL
KSEL,S,KP,,KP(X1+GIT,Y1+RAD1,0)
*GET,KP1,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1-RAD1,Y1-GIT,0)
*GET,KP2,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1-RAD1,Y1+RAD1,0)
*GET,KP3,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1+GIT+BUFF,Y1+RAD1,0)
*GET,KP4,KP,,NUM,MAX

KSEL,ALL
KSEL,S,KP,,KP(X1-RAD1,Y1-GIT-BUFF,0)
*GET,KP5,KP,,NUM,MAX

LSEL,S,LOC,Y,Y1+RAD1
LSEL,R,LOC,X,X1+GIT,X1+GIT+BUFF
CM,LN1,LINE

LSEL,S,LOC,Y,Y1-GIT-BUFF,Y1-GIT
LSEL,R,LOC,X,X1-RAD1
CM,LN2,LINE

LSEL,S,RADIUS,,RAD1+GIT
LSEL,R,LOC,X,X1-RAD1,X1+GIT+BUFF
CM,LN3,LINE

LSEL,NONE
KSEL,ALL
LARC,KP4,KP5,KP3,RAD1+GIT+BUFF
CMSEL,A,LN1,LINE
CMSEL,A,LN2,LINE
CMSEL,A,LN3,LINE
KSLL,,1
NSLL,,1
NUMMEG,NODE
NUMMRG,KP
ASEL,NONE
AL,ALL
AATT,THIS_MAT,,THIS_ET,BOT_RGT_CS
MSHKEY,1
MSHAPE,0
AMESH,ALL

*ENDIF
		
			
ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE,1e-5
NUMMRG,KP,1e-5