!=======================================================================
! TF_cfill.f - Side fillers of a pancake-wound WP.
! Not called by the current STR_MODEL.f.
!=======================================================================
/PREP7
LSEL,,LCCAT
LDELE,ALL
ALLSEL,ALL,ALL
NUMCMP,LINE
*GET,ULT_LN,LINE,,NUM,MAX

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! SIDE PANCAKE FILLER
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THIS_MAT = STEEL_FIL_MAT
THIS_ET = STEEL_FIL_ET
THAT_MAT = JCK_MAT
ELM_SZ = 2*DLIT

ESIZE,0.005

!!
!! LEFT CORNER
!!
	
i = GRADES-1
k = 1

CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
KSEL,S,LOC,Y,-HJH(i,k)-ICIT-LWIT*2
KSEL,R,LOC,X,-HJW(i,k)-ICIT,HJW(i,k)+ICIT
LSLK,,1
CM,LN1,LINE

*GET,Xs1,KP,,MNLOC,X
*GET,Yu,KP,,MNLOC,Y
KSEL,ALL
KSEL,S,KP,,KP(Xs1,Yu,0)
*GET,KP1,KP,,NUM,MAX

KSEL,S,LOC,Y,-HJH(i+1,k)*2-HJH(i,k)-ICIT*3-LWIT*2,-HJH(i,k)-ICIT-LWIT*2
KSEL,R,LOC,X,HJW(i,k)+ICIT
LSLK,,1
CM,LN2,LINE

*GET,Xs2,KP,,MNLOC,X
*GET,Yu,KP,,MNLOC,Y
KSEL,ALL
KSEL,S,KP,,KP(Xs2,Yu,0)
*GET,KP2,KP,,NUM,MAX

KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX

X1_LFTC = -(HJW(i,k)+ICIT)
Y1_LFTC = -HJH(i+1,k)*2-HJH(i,k)-ICIT*3-LWIT*2+RAD1
X2_LFTC = -(HJW(i,k)+ICIT)+RAD1
Y2_LFTC = -HJH(i+1,k)*2-HJH(i,k)-ICIT*3-LWIT*2+RAD1
X3_LFTC = -(HJW(i,k)+ICIT)+RAD1
Y3_LFTC = -HJH(i+1,k)*2-HJH(i,k)-ICIT*3-LWIT*2
K,ULT_KP+1,X1_LFTC,Y1_LFTC
K,ULT_KP+2,X2_LFTC,Y2_LFTC
K,ULT_KP+3,X3_LFTC,Y3_LFTC

LSEL,NONE
L,KP1,ULT_KP+1
LARC,ULT_KP+1,ULT_KP+3,ULT_KP+2,RAD1
L,KP2,ULT_KP+3
CMSEL,A,LN1,LINE
CMSEL,A,LN2,LINE
KSLL,,1
NSLL,,1
NUMMEG,NODE
NUMMRG,KP
ASEL,NONE
AL,ALL
AATT,THIS_MAT,,THIS_ET
! LSEL,S,LINE,,ULT_LN+2,ULT_LN+3
! LCCAT,ALL
MSHKEY,0
MSHAPE,0
AMESH,ALL
			
!!
!! RIGHT CORNER
!!
	
i = GRADES-1
k = NT_HIGHF

CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
KSEL,S,LOC,Y,-HJH(i,k)-ICIT-LWIT*2
KSEL,R,LOC,X,-HJW(i,k)-ICIT,HJW(i,k)+ICIT
LSLK,,1
CM,LN1,LINE

*GET,Xs1,KP,,MXLOC,X
*GET,Yu,KP,,MNLOC,Y
KSEL,ALL
KSEL,S,KP,,KP(Xs1,Yu,0)
*GET,KP1,KP,,NUM,MAX

KSEL,S,LOC,Y,-HJH(i+1,k-2)*2-HJH(i,k)-ICIT*3-LWIT*2,-HJH(i,k)-ICIT-LWIT*2
KSEL,R,LOC,X,-(HJW(i,k)+ICIT)
LSLK,,1
CM,LN2,LINE

*GET,Xs2,KP,,MNLOC,X
*GET,Yu,KP,,MNLOC,Y
KSEL,ALL
KSEL,S,KP,,KP(Xs2,Yu,0)
*GET,KP2,KP,,NUM,MAX

KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX

X1_LFTC = (HJW(i,k)+ICIT)
Y1_LFTC = -HJH(i+1,k-2)*2-HJH(i,k)-ICIT*3-LWIT*2+RAD1
X2_LFTC = (HJW(i,k)+ICIT)-RAD1
Y2_LFTC = -HJH(i+1,k-2)*2-HJH(i,k)-ICIT*3-LWIT*2+RAD1
X3_LFTC = (HJW(i,k)+ICIT)-RAD1
Y3_LFTC = -HJH(i+1,k-2)*2-HJH(i,k)-ICIT*3-LWIT*2
K,ULT_KP+1,X1_LFTC,Y1_LFTC
K,ULT_KP+2,X2_LFTC,Y2_LFTC
K,ULT_KP+3,X3_LFTC,Y3_LFTC

LSEL,NONE
L,KP1,ULT_KP+1
LARC,ULT_KP+1,ULT_KP+3,ULT_KP+2,RAD1
L,KP2,ULT_KP+3
CMSEL,A,LN1,LINE
CMSEL,A,LN2,LINE
KSLL,,1
NSLL,,1
NUMMEG,NODE
NUMMRG,KP
ASEL,NONE
AL,ALL
AATT,THIS_MAT,,THIS_ET
! LSEL,S,LINE,,ULT_LN+2,ULT_LN+3
! LCCAT,ALL
MSHKEY,0
MSHAPE,0
AMESH,ALL
			
ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE,1e-6
NUMMRG,KP,1e-6


