!=======================================================================
! TF_dlins.f - Double-layer insulation (DLIT) of a double-layer wound WP.
! Not called by the current STR_MODEL.f.
!=======================================================================
/PREP7
LSEL,,LCCAT
LDELE,ALL
ALLSEL,ALL,ALL
NUMCMP,LINE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! DOUBLE PANCAKE INSULATION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THIS_MAT = DLINS_MAT
THIS_ET = DLINS_ET
THAT_MAT = JCK_MAT
ELM_SZ = 2*DLIT

i = 1
	k = 1
	CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
	KSEL,,LOC,Y,HJH(i,k)+ICIT
	LSLK,,1
	CM,THIS_DLINS,LINE 
	*GET,XREF,KP,,MNLOC,X
	
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	KSEL,NONE
	K,ULT_KP+1,XREF,HJH(i,k)+ICIT
	K,ULT_KP+2,XREF,HJH(i,k)+ICIT+DLIT
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		DLINS_EXT_LN = LSNEXT(0)
		CMSEL,A,THIS_DLINS,LINE
		NSLL,,1
			ASEL,NONE
			ADRAG,ALL,,,,,,DLINS_EXT_LN
			KSLL,,1
			NSLL,,1
			NUMMRG,NODE
			NUMMRG,KP
			ALLSEL,BELOW,AREA
			AATT,THIS_MAT,,THIS_ET,TOP_CS
			MSHKEY,1
			MSHAPE,0
			ESIZE,ELM_SZ
			AMESH,ALL

*DO,i,2,GRADES,2
	*IF,i,LE,NL_HIGHF,THEN
		k = 1
		CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
		KSEL,,LOC,Y,-HJH(i,k)-ICIT
		LSLK,,1
		CM,THIS_DLINS,LINE 
		*GET,X1,KP,,MNLOC,X
		*GET,X2,KP,,MXLOC,X
		KSEL,,LOC,Y,-HJH(i,k)-ICIT-2*DLIT
		LSLK,,1
		CM,THAT_DLINS,LINE 
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX
		KSEL,NONE
		K,ULT_KP+1,X1,-HJH(i,k)-ICIT
		K,ULT_KP+2,X1,-HJH(i,k)-ICIT-2*DLIT
		K,ULT_KP+3,X2,-HJH(i,k)-ICIT
		K,ULT_KP+4,X2,-HJH(i,k)-ICIT-2*DLIT
			LSEL,NONE
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+3,ULT_KP+4
			CMSEL,A,THIS_DLINS,LINE
			CMSEL,A,THAT_DLINS,LINE
			KSLL,,1
			NSLL,,1
			NUMMRG,NODE
			NUMMRG,KP
				ASEL,NONE
				AL,ALL
				ALLSEL,BELOW,AREA
				AATT,THIS_MAT,,THIS_ET,TOP_CS
				MSHKEY,0
				MSHAPE,0
				LCCAT,THIS_DLINS
				LCCAT,THAT_DLINS
				ESIZE,ELM_SZ
				AMESH,ALL
	*ELSEIF,i,GT,NL_HIGHF,AND,i,EQ,GRADES,THEN
		k = 1
		CSYS,MAX_CS+8*(NL_HIGHF*NT_HIGHF+NT_LOWF*(i-NL_HIGHF-1)+(k-1))+2
		KSEL,,LOC,Y,-HJH(i,k)-ICIT
		LSLK,,1
		CM,THIS_DLINS,LINE 
		*GET,XREF,KP,,MNLOC,X
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX
		KSEL,NONE
		K,ULT_KP+1,XREF,-HJH(i,k)-ICIT
		K,ULT_KP+2,XREF,-HJH(i,k)-ICIT-DLIT
			LSEL,NONE
			L,ULT_KP+1,ULT_KP+2
			DLINS_EXT_LN = LSNEXT(0)
			CMSEL,A,THIS_DLINS,LINE
			NSLL,,1
				ASEL,NONE
				ADRAG,ALL,,,,,,DLINS_EXT_LN
				KSLL,,1
				NSLL,,1
				NUMMRG,NODE
				NUMMRG,KP
				ALLSEL,BELOW,AREA
				AATT,THIS_MAT,,THIS_ET,BOT_CS
				MSHKEY,1
				MSHAPE,0
				ESIZE,ELM_SZ
				AMESH,ALL
	*ELSE
		k = 1
		CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
		KSEL,,LOC,Y,-HJH(i,k)-ICIT
		LSLK,,1
		CM,THIS_DLINS,LINE 
		*GET,X1,KP,,MNLOC,X
		*GET,X2,KP,,MXLOC,X
		KSEL,,LOC,Y,-HJH(i,k)-ICIT-2*DLIT
		LSLK,,1
		CM,THAT_DLINS,LINE 
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX
		KSEL,NONE
		K,ULT_KP+1,X1,-HJH(i,k)-ICIT
		K,ULT_KP+2,X1,-HJH(i,k)-ICIT-2*DLIT
		K,ULT_KP+3,X2,-HJH(i,k)-ICIT
		K,ULT_KP+4,X2,-HJH(i,k)-ICIT-2*DLIT
			LSEL,NONE
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+3,ULT_KP+4
			CMSEL,A,THIS_DLINS,LINE
			CMSEL,A,THAT_DLINS,LINE
			KSLL,,1
			NSLL,,1
			NUMMRG,NODE
			NUMMRG,KP
				ASEL,NONE
				AL,ALL
				ALLSEL,BELOW,AREA
				AATT,THIS_MAT,,THIS_ET,TOP_CS
				MSHKEY,0
				MSHAPE,0
				LCCAT,THIS_DLINS
				LCCAT,THAT_DLINS
				ESIZE,ELM_SZ
				AMESH,ALL
	*ENDIF
*ENDDO

ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE
NUMMRG,KP

CSYS,REF_CS
ALLSEL,ALL,ALL
SELTOL,1.E-6
*GET,XREF,KP,,MNLOC,X
KSEL,,LOC,X,XREF
LSLK,,1
KSLL,,1
NSLL,,1
NUMMRG,NODE
NUMMRG,KP
CM,THIS_DLINS,LINE 
*GET,YREF,KP,,MNLOC,Y

KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,-WPW_HIGHF/2,YREF
K,ULT_KP+2,-WPW_HIGHF/2-DLIT,YREF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	DLINS_EXT_LN = LSNEXT(0)
	CMSEL,A,THIS_DLINS,LINE
	NSLL,,1
		ASEL,NONE
		ADRAG,ALL,,,,,,DLINS_EXT_LN
		ALLSEL,BELOW,AREA
		AATT,THIS_MAT,,THIS_ET,LFT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
		ALLSEL,BELOW,AREA
		*GET,X1_LFTC,KP,,MNLOC,X
		*GET,Y1_LFTC,KP,,MNLOC,Y
		*GET,X2_LFTC,KP,,MXLOC,X
		*GET,Y2_LFTC,KP,,MNLOC,Y
		
CSYS,REF_CS
ALLSEL,ALL,ALL
SELTOL,1.E-6
*GET,XREF,KP,,MXLOC,X
KSEL,,LOC,X,XREF
LSLK,,1
KSLL,,1
NSLL,,1
NUMMRG,NODE
NUMMRG,KP
CM,THIS_DLINS,LINE 
*GET,YREF,KP,,MNLOC,Y

KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,WPW_HIGHF/2,YREF
K,ULT_KP+2,WPW_HIGHF/2+DLIT,YREF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	DLINS_EXT_LN = LSNEXT(0)
	CMSEL,A,THIS_DLINS,LINE
	NSLL,,1
		ASEL,NONE
		ADRAG,ALL,,,,,,DLINS_EXT_LN
		ALLSEL,BELOW,AREA
		AATT,THIS_MAT,,THIS_ET,RGT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
		*GET,X1_RGTC,KP,,MNLOC,X
		*GET,Y1_RGTC,KP,,MNLOC,Y
		*GET,X2_RGTC,KP,,MXLOC,X
		*GET,Y2_RGTC,KP,,MNLOC,Y

ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE
NUMMRG,KP

!! LEFT CORNER
XCENT_LFTC = X2_LFTC+RAD1
YCENT_LFTC = WP_INTR+BUFF+GIT+DLIT+RAD1
*GET,MAX_CS,CDSY,,NUM,MAX
LFTC_CS = MAX_CS+1
LOCAL,LFTC_CS,1,XCENT_LFTC,YCENT_LFTC,,225
CSYS,REF_CS

ASEL,,MAT,,THIS_MAT,,,1
ALLSEL,BELOW,AREA
*GET,YBOTT,KP,,MNLOC,Y
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	KSEL,NONE
	K,ULT_KP+1,X2_LFTC,Y2_LFTC
	K,ULT_KP+2,X1_LFTC,Y1_LFTC
	K,ULT_KP+3,X1_LFTC,YCENT_LFTC
	K,ULT_KP+4,X2_LFTC,YCENT_LFTC
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+2,ULT_KP+3
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+4,ULT_KP+1
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,,THIS_ET,LFT_CS
			THIS_AREA = ARNEXT(0)
			ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
			ALLSEL,BELOW,AREA
			NUMMRG,NODE
			NUMMRG,KP
			ASEL,,AREA,,THIS_AREA
			MSHKEY,1
			MSHAPE,0
			ESIZE,ELM_SZ
			AMESH,ALL
			
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	KSEL,NONE
	K,ULT_KP+1,X2_LFTC,YCENT_LFTC
	K,ULT_KP+2,X1_LFTC,YCENT_LFTC
	K,ULT_KP+3,XCENT_LFTC,WP_INTR+BUFF+GIT
	K,ULT_KP+4,XCENT_LFTC,WP_INTR+BUFF+GIT+DLIT
	K,ULT_KP+5,XCENT_LFTC,YCENT_LFTC
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		LARC,ULT_KP+2,ULT_KP+3,ULT_KP+5,RAD1+DLIT
		L,ULT_KP+3,ULT_KP+4
		LARC,ULT_KP+4,ULT_KP+1,ULT_KP+5,RAD1
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,,THIS_ET,LFTC_CS
			THIS_AREA = ARNEXT(0)
			ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
			ALLSEL,BELOW,AREA
			NUMMRG,NODE
			NUMMRG,KP
			ASEL,,AREA,,THIS_AREA
			MSHKEY,1
			MSHAPE,0
			ESIZE,ELM_SZ
			AMESH,ALL
			
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	KSEL,NONE
	K,ULT_KP+1,XCENT_LFTC,WP_INTR+BUFF+GIT+DLIT
	K,ULT_KP+2,XCENT_LFTC,WP_INTR+BUFF+GIT
	K,ULT_KP+3,-WPW_LOWF/2+DLIT,WP_INTR+BUFF+GIT
	K,ULT_KP+4,-WPW_LOWF/2+DLIT,WP_INTR+BUFF+GIT+DLIT
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+2,ULT_KP+3
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+4,ULT_KP+1
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,,THIS_ET,BOT_CS
			THIS_AREA = ARNEXT(0)
			ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
			ALLSEL,BELOW,AREA
			NUMMRG,NODE
			NUMMRG,KP
			ASEL,,AREA,,THIS_AREA
			MSHKEY,1
			MSHAPE,0
			ESIZE,ELM_SZ
			AMESH,ALL
		

!! RIGHT CORNER
XCENT_RGTC = X1_RGTC-RAD1
YCENT_RGTC = WP_INTR+BUFF+GIT+DLIT+RAD1
*GET,MAX_CS,CDSY,,NUM,MAX
RGTC_CS = MAX_CS+1
LOCAL,RGTC_CS,1,XCENT_RGTC,YCENT_RGTC,,-45
CSYS,REF_CS

ASEL,,MAT,,THIS_MAT,,,1
ALLSEL,BELOW,AREA
*GET,YBOTT,KP,,MNLOC,Y
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	KSEL,NONE
	K,ULT_KP+1,X2_RGTC,Y2_RGTC
	K,ULT_KP+2,X1_RGTC,Y1_RGTC
	K,ULT_KP+3,X1_RGTC,YCENT_RGTC
	K,ULT_KP+4,X2_RGTC,YCENT_RGTC
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+2,ULT_KP+3
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+4,ULT_KP+1
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,,THIS_ET,RGT_CS
			THIS_AREA = ARNEXT(0)
			ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
			ALLSEL,BELOW,AREA
			NUMMRG,NODE
			NUMMRG,KP
			ASEL,,AREA,,THIS_AREA
			MSHKEY,1
			MSHAPE,0
			ESIZE,ELM_SZ
			AMESH,ALL
			
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	KSEL,NONE
	K,ULT_KP+1,X2_RGTC,YCENT_RGTC
	K,ULT_KP+2,X1_RGTC,YCENT_RGTC
	K,ULT_KP+3,XCENT_RGTC,WP_INTR+BUFF+GIT+DLIT
	K,ULT_KP+4,XCENT_RGTC,WP_INTR+BUFF+GIT
	K,ULT_KP+5,XCENT_RGTC,YCENT_RGTC
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		LARC,ULT_KP+2,ULT_KP+3,ULT_KP+5,RAD1
		L,ULT_KP+3,ULT_KP+4
		LARC,ULT_KP+4,ULT_KP+1,ULT_KP+5,RAD1+DLIT
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,,THIS_ET,RGTC_CS
			THIS_AREA = ARNEXT(0)
			ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
			ALLSEL,BELOW,AREA
			NUMMRG,NODE
			NUMMRG,KP
			ASEL,,AREA,,THIS_AREA
			MSHKEY,1
			MSHAPE,0
			ESIZE,ELM_SZ
			AMESH,ALL
			
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	KSEL,NONE
	K,ULT_KP+1,XCENT_RGTC,WP_INTR+BUFF+GIT
	K,ULT_KP+2,XCENT_RGTC,WP_INTR+BUFF+GIT+DLIT
	K,ULT_KP+3,WPW_LOWF/2-DLIT,WP_INTR+BUFF+GIT+DLIT
	K,ULT_KP+4,WPW_LOWF/2-DLIT,WP_INTR+BUFF+GIT
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+2,ULT_KP+3
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+4,ULT_KP+1
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,,THIS_ET,BOT_CS
			THIS_AREA = ARNEXT(0)
			ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
			ALLSEL,BELOW,AREA
			NUMMRG,NODE
			NUMMRG,KP
			ASEL,,AREA,,THIS_AREA
			MSHKEY,1
			MSHAPE,0
			ESIZE,ELM_SZ
			AMESH,ALL
		
ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE
NUMMRG,KP

