!=======================================================================
! TF_dpins.f - Double-pancake insulation (DPIT) of a pancake-wound WP.
! Not called by the current STR_MODEL.f.
!=======================================================================
/PREP7
LSEL,,LCCAT
LDELE,ALL
ALLSEL,ALL,ALL
NUMCMP,LINE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! DOUBLE PANCAKE INSULATION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THIS_MAT = DPINS_MAT
THIS_ET = DPINS_ET
THAT_MAT = JCK_MAT

*IF,MOD(DPC,2),EQ,0,THEN
	*DO,i,1,NT_LOWF/2,2
	CSYS,REF_CS
	KSEL,,LOC,X,-DPIT-(LTOT+DPIT)*(i-1)
	LSLK,,1
	CM,THIS_DPINS,LINE 
	
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	K,ULT_KP+1,-DPIT-(LTOT+DPIT)*(i-1),WP_INTR+WPH-GIT-DPIT
	K,ULT_KP+2,-(LTOT+DPIT)*(i-1),WP_INTR+WPH-GIT-DPIT
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		DPINS_EXT_LN = LSNEXT(0)
		CMSEL,A,THIS_DPINS,LINE
		NSLL,,1
			ASEL,NONE
			ADRAG,ALL,,,,,,DPINS_EXT_LN
			ALLSEL,BELOW,AREA
			AATT,THIS_MAT,,THIS_ET
			MSHKEY,1
			MSHAPE,0
			AMESH,ALL
	*ENDDO
	*DO,2,NT_LOWF-1,2
	CSYS,REF_CS
	KSEL,,LOC,X,-LTOT-(LTOT+DPIT)*(i-1)
	LSLK,,1
	CM,THIS_DPINS,LINE 
	
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	K,ULT_KP+1,-LTOT-(LTOT+DPIT)*(i-1),WP_INTR+WPH-GIT-DPIT
	K,ULT_KP+2,-(LTOT+DPIT)*(i),WP_INTR+WPH-GIT-DPIT
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		DPINS_EXT_LN = LSNEXT(0)
		CMSEL,A,THIS_DPINS,LINE
		NSLL,,1
			ASEL,NONE
			ADRAG,ALL,,,,,,DPINS_EXT_LN
			ALLSEL,BELOW,AREA
			AATT,THIS_MAT,,THIS_ET
			MSHKEY,1
			MSHAPE,0
			AMESH,ALL
	*ENDDO
*ELSE
	*DO,i,1,NT_LOWF/2-1,2
	CSYS,REF_CS
	KSEL,,LOC,X,-LTOT-(LTOT+DPIT)*(i-1)
	LSLK,,1
	CM,THIS_DPINS,LINE 
	
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	K,ULT_KP+1,-LTOT-(LTOT+DPIT)*(i-1),WP_INTR+WPH-GIT-DPIT
	K,ULT_KP+2,-(LTOT+DPIT)*(i),WP_INTR+WPH-GIT-DPIT
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		DPINS_EXT_LN = LSNEXT(0)
		CMSEL,A,THIS_DPINS,LINE
		NSLL,,1
			ASEL,NONE
			ADRAG,ALL,,,,,,DPINS_EXT_LN
			ALLSEL,BELOW,AREA
			AATT,THIS_MAT,,THIS_ET
			MSHKEY,1
			MSHAPE,0
			AMESH,ALL
	*ENDDO
	*DO,i,2,NT_LOWF/2,2
	CSYS,REF_CS
	KSEL,,LOC,X,-DPIT-(LTOT+DPIT)*(i-1)
	LSLK,,1
	CM,THIS_DPINS,LINE 
	
	KSEL,ALL
	*GET,ULT_KP,KP,,NUM,MAX
	K,ULT_KP+1,-DPIT-(LTOT+DPIT)*(i-1),WP_INTR+WPH-GIT-DPIT
	K,ULT_KP+2,-(LTOT+DPIT)*(i-1),WP_INTR+WPH-GIT-DPIT
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		DPINS_EXT_LN = LSNEXT(0)
		CMSEL,A,THIS_DPINS,LINE
		NSLL,,1
			ASEL,NONE
			ADRAG,ALL,,,,,,DPINS_EXT_LN
			ALLSEL,BELOW,AREA
			AATT,THIS_MAT,,THIS_ET
			MSHKEY,1
			MSHAPE,0
			AMESH,ALL
	*ENDDO
*ENDIF

CSYS,SYMM_PLANE
ASEL,,MAT,,THIS_MAT,,,1
ALLSEL,BELOW,AREA
ARSYM,X,ALL

ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE
NUMMRG,KP


