!=======================================================================
! TF_gins.f - Ground insulation of a WP with layers of equal width (older version).
! Not called by the current STR_MODEL.f.
!=======================================================================
/PREP7
LSEL,,LCCAT
LDELE,ALL
ALLSEL,ALL,ALL
NUMCMP,LINE
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!! GROUND INSULATION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THAT_MAT = JCK_MAT
THIS_MAT = GINS_MAT
THIS_ET = GINS_ET
THIS_REAL = GINS_MAT
ELM_SZ = (GIT)/2

*GET,MAX_CS_GIT,CDSY,0,NUM,MAX
TOP_CS = MAX_CS_GIT+1
RGT_CS = MAX_CS_GIT+2
BOT_CS = MAX_CS_GIT+3
LFT_CS = MAX_CS_GIT+4
BOT_LFT_CS = MAX_CS_GIT+5
BOT_RGT_CS = MAX_CS_GIT+6

ALLSEL,ALL,ALL
CSYS,REF_CS
*GET,Xmin,KP,,MNLOC,X
*GET,Ymin,KP,,MNLOC,Y
*GET,Xmax,KP,,MXLOC,X
*GET,Ymax,KP,,MXLOC,Y

LOCAL,TOP_CS,0,0,Ymax+GIT+BUFF,0.0,90
LOCAL,RGT_CS,0,Xmax+GIT+BUFF,(Ymax+Ymin)/2,0.0,
LOCAL,LFT_CS,0,Xmin-GIT-BUFF,(Ymax+Ymin)/2,0.0,180
LOCAL,BOT_CS,0,0,Ymin-GIT-BUFF,0.0,270
LOCAL,BOT_LFT_CS,1,Xmin+RAD1,Ymin+RAD1,0.0,225
LOCAL,BOT_RGT_CS,1,Xmax-RAD1,Ymin+RAD1,0.0,315

!!
!! TOP
!!
SELTOL,1e-4
CSYS,REF_CS
KSEL,,LOC,Y,Ymax!INNLEG_OUTR-CASE_THICK-GIT-BUFF
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF,YREF+GIT
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,GIT_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP,1e-3
		ASEL,NONE
		ADRAG,ALL,,,,,,GIT_EXT_LN
		AATT,THIS_MAT,,THIS_ET,TOP_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
	
!!
!! LEFT
!!
SELTOL,1e-4
CSYS,REF_CS
KSEL,,LOC,X,Xmin!-WPW_HIGHF/2
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF-GIT,YREF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,GIT_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		ASEL,NONE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP,1e-3
		ASEL,NONE
		ADRAG,ALL,,,,,,GIT_EXT_LN
		AATT,THIS_MAT,,THIS_ET,LFT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
		
!!
!! RIGHT
!!
SELTOL,1e-4
CSYS,REF_CS
KSEL,,LOC,X,Xmax!WPW_HIGHF/2
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF+GIT,YREF
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,GIT_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		ASEL,NONE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE 
		NUMMRG,KP,1e-3
		ASEL,NONE
		ADRAG,ALL,,,,,,GIT_EXT_LN
		AATT,THIS_MAT,,THIS_ET,RGT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL
		
!!
!! BOTT
!!
SELTOL,1e-4
CSYS,REF_CS
KSEL,,LOC,Y,Ymin! WP_INTR+GIT+BUFF
LSLK,,1
*GET,XREF,KP,,MNLOC,X
*GET,YREF,KP,,MXLOC,Y
CM,THIS_LN,LINE
KSEL,ALL
*GET,ULT_KP,KP,,NUM,MAX
KSEL,NONE
K,ULT_KP+1,XREF,YREF
K,ULT_KP+2,XREF,YREF-GIT
	LSEL,NONE
	L,ULT_KP+1,ULT_KP+2
	CM,GIT_EXT_LN,LINE
	CMSEL,A,THIS_LN,LINE
		ASEL,NONE
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP,1e-3
		ASEL,NONE
		ADRAG,ALL,,,,,,GIT_EXT_LN
		AATT,THIS_MAT,,THIS_ET,BOT_CS
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL

*IF,NL_LOWF,NE,0,THEN
	!!
	!! LEFT CORNER
	!!
	i = GRADES-1
	k = 1

	CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
	ASEL,S,MAT,,STEEL_FIL_MAT
	ASEL,R,LOC,X,-HJW(i,k)-ICIT,HJW(i,k)+ICIT
	ALLSEL,BELOW,AREA
	*GET,X1,KP,,MNLOC,X
	*GET,Y1,KP,,MNLOC,Y

	KSEL,ALL
	KSEL,S,KP,,KP(X1,Y1+RAD1,0)
	*GET,KP1,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1+RAD1,Y1,0)
	*GET,KP2,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1+RAD1,Y1+RAD1,0)
	*GET,KP3,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1-GIT,Y1+RAD1,0)
	*GET,KP4,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1+RAD1,Y1-GIT,0)
	*GET,KP5,KP,,NUM,MAX

	LSEL,S,LOC,Y,Y1+RAD1
	LSEL,R,LOC,X,X1-GIT,X1
	CM,LN1,LINE

	LSEL,S,LOC,Y,Y1-GIT,Y1
	LSEL,R,LOC,X,X1+RAD1
	CM,LN2,LINE

	LSEL,S,RADIUS,,RAD1
	LSEL,R,LOC,X,X1,X1+RAD1
	CM,LN3,LINE

	LSEL,NONE
	KSEL,ALL
	LARC,KP4,KP5,KP3,RAD1+GIT
	CMSEL,A,LN1,LINE
	CMSEL,A,LN2,LINE
	CMSEL,A,LN3,LINE
	KSLL,,1
	NSLL,,1
	NUMMEG,NODE
	NUMMRG,KP
	ASEL,NONE
	AL,ALL
	AATT,THIS_MAT,,THIS_ET,BOT_LFT_CS
	MSHKEY,1
	MSHAPE,0
	AMESH,ALL
				
	!!
	!! RIGHT CORNER
	!!
	i = GRADES-1
	k = NT_HIGHF

	CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2
	ASEL,S,MAT,,STEEL_FIL_MAT
	ASEL,R,LOC,X,-HJW(i,k)-ICIT,HJW(i,k)+ICIT
	ALLSEL,BELOW,AREA
	*GET,X1,KP,,MXLOC,X
	*GET,Y1,KP,,MNLOC,Y

	KSEL,ALL
	KSEL,S,KP,,KP(X1,Y1+RAD1,0)
	*GET,KP1,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1-RAD1,Y1,0)
	*GET,KP2,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1-RAD1,Y1+RAD1,0)
	*GET,KP3,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1+GIT,Y1+RAD1,0)
	*GET,KP4,KP,,NUM,MAX

	KSEL,ALL
	KSEL,S,KP,,KP(X1-RAD1,Y1-GIT,0)
	*GET,KP5,KP,,NUM,MAX

	LSEL,S,LOC,Y,Y1+RAD1
	LSEL,R,LOC,X,X1+GIT,X1
	CM,LN1,LINE

	LSEL,S,LOC,Y,Y1-GIT,Y1
	LSEL,R,LOC,X,X1-RAD1
	CM,LN2,LINE

	LSEL,S,RADIUS,,RAD1
	LSEL,R,LOC,X,X1-RAD1,1
	CM,LN3,LINE

	LSEL,NONE
	KSEL,ALL
	LARC,KP4,KP5,KP3,RAD1+GIT
	CMSEL,A,LN1,LINE
	CMSEL,A,LN2,LINE
	CMSEL,A,LN3,LINE
	KSLL,,1
	NSLL,,1
	NUMMEG,NODE
	NUMMRG,KP
	ASEL,NONE
	AL,ALL
	AATT,THIS_MAT,,THIS_ET,BOT_RGT_CS
	MSHKEY,1
	MSHAPE,0
	AMESH,ALL
*ENDIF
				
ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE,1e-5
NUMMRG,KP,1e-5