!=======================================================================
! TF_jck.f - Jackets of a WP with layers of equal width (older version of
! TF_jck_trpz.f). Not called by the current STR_MODEL.f.
!=======================================================================
/PREP7
LSEL,,LCCAT
LDELE,ALL
ALLSEL,ALL,ALL
NUMCMP,LINE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! JACKETS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THIS_COMP = 'JCK'
THIS_MAT = JCK_MAT
THAT_MAT = JCK_MAT
THIS_ET = JCK_ET
ELM_SZ = 0.001 ! JT_h(1,1)/4
ARC_DIV = 6

! ESIZE,ELM_SZ

*DO,i,1,GRADES
	*IF,i,LE,NL_HIGHF,THEN
		*DO,k,1,NT_HIGHF
		! Geometric parameters
		CHAM = 0.0
		! R(i,k) = JT_h(i,k)/2			 !Jacket internal radius
		R_N = R(i,k)
		EXT_RAD = R_N+JT_h(i,k)       	 !Jacket external radius		
		ELM_SZ = JT_h(i,k)/4
		
		JH_N = JH(i,k)			!Half Jacket Height
		JW_N = 2*HJW(i,k)       !Half jacket width
		HCW_N = HCW(i,k)        !Half Conductor width
		HCH_N = HCH(i,k)        !Half Conductor Height
		JT_Nh = JT_h(i,k)
		JT_Nw = JT_w(i,k)

		LHI_N = LHI(i,k)
		LWI_N = LWI(i,k)

		! Local CS to identify cable centre and later define orthotropic material properties
		CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2

		THIS_REAL = 100+NT_HIGHF*(i-1)+k
		THIS_CS = MAX_CS+8*((k-1)+NT_HIGHF*(i-1))
		
		! create jacket areas
		*IF,CABLE_TYPE(i,1),EQ,'RIS',THEN
			! TOP
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,HCH_N
			K,ULT_KP+2,HCH_N*cos(pi/4),HCH_N*sin(pi/4)
			K,ULT_KP+3,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+4,,HCH_N+JT_Nh
			K,ULT_KP+5,, 
			LSEL,NONE				
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+5,HCH_N
			*GET,ULT_LN,LINE,,NUM,MAX
			CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+3,ULT_KP+4
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3		
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!TP-RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCH_N*cos(pi/4),HCH_N*sin(pi/4)
			K,ULT_KP+2,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+3,HCW_N+JT_Nw,HCH_N-R_N
			K,ULT_KP+4,HCW_N+JT_Nw-EXT_RAD,HCH_N+JT_Nh-EXT_RAD			
			LSEL,NONE
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+1,ULT_KP+3
			LARC,ULT_KP+2,ULT_KP+3,ULT_KP+4,EXT_RAD
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			! LESIZE,ALL,,,ARC_DIV
			! RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCH_N*cos(pi/4),HCH_N*sin(pi/4)
			K,ULT_KP+2,HCW_N+JT_Nw,HCH_N+JT_Nh-EXT_RAD
			K,ULT_KP+3,HCW_N+JT_Nw,-(HCH_N+JT_Nh-EXT_RAD)
			K,ULT_KP+4,HCH_N*cos(pi/4),-HCH_N*sin(pi/4)
			K,ULT_KP+5,,,
			LSEL,NONE
			LARC,ULT_KP+1,ULT_KP+4,ULT_KP+5,HCH_N
			CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+2,ULT_KP+3
			L,ULT_KP+4,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!BT-RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCH_N*cos(pi/4),-HCH_N*sin(pi/4)
			K,ULT_KP+2,HCW_N-R_N,-HCH_N-JT_Nh
			K,ULT_KP+3,HCW_N+JT_Nw,-HCH_N+R_N
			K,ULT_KP+4,HCW_N+JT_Nw-EXT_RAD,-HCH_N-JT_Nh+EXT_RAD			
			LSEL,NONE
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+1,ULT_KP+3
			LARC,ULT_KP+2,ULT_KP+3,ULT_KP+4,EXT_RAD
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			! BOT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,-HCH_N
			K,ULT_KP+2,HCH_N*cos(pi/4),-HCH_N*sin(pi/4)
			K,ULT_KP+3,HCW_N-R_N,-HCH_N-JT_Nh
			K,ULT_KP+4,,-HCH_N-JT_Nh
			K,ULT_KP+5,, 
			LSEL,NONE										
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+5,HCH_N
			*GET,ULT_LN,LINE,,NUM,MAX
			CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3
			L,ULT_KP+3,ULT_KP+4
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+3
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
		*ELSE
			! TOP
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,HCH_N
			K,ULT_KP+2,HCW_N-R_N,HCH_N
			K,ULT_KP+3,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+4,,HCH_N+JT_Nh
			LSEL,NONE
			L,ULT_KP+3,ULT_KP+4
			CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+1,ULT_KP+2
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!TP-RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCW_N-R_N,HCH_N
			K,ULT_KP+2,HCW_N,HCH_N-R_N
			K,ULT_KP+3,HCW_N+JT_Nw,HCH_N-R_N
			!K,ULT_KP+4,HCW_N+JT_Nw,HCH_N+JT_Nh-EXT_RAD
			K,ULT_KP+5,HCW_N-R_N,HCH_N+JT_Nh
			!K,ULT_KP+6,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+7,HCW_N-R_N,HCH_N-R_N
			!K,ULT_KP+8,HCW_N+JT_Nw-EXT_RAD,HCH_N+JT_Nh-EXT_RAD
			LSEL,NONE
			! LARC,ULT_KP+4,ULT_KP+5,ULT_KP+8,EXT_RAD
			LARC,ULT_KP+3,ULT_KP+5,ULT_KP+7,EXT_RAD
			!L,ULT_KP+3,ULT_KP+4
			!L,ULT_KP+5,ULT_KP+6
			LESIZE,ALL,,,ARC_DIV
			CM,TRG_%THIS_COMP%_%THIS_REAL%,LINE
			! L,ULT_KP+6,ULT_KP+1
			
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+7,R_N
			LESIZE,ALL,,,ARC_DIV
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+5,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			! LESIZE,ALL,,,ARC_DIV
			! RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCW_N,HCH_N-R_N
			K,ULT_KP+2,HCW_N,-HCH_N+R_N
			K,ULT_KP+3,HCW_N+JT_Nw,-HCH_N+R_N
			K,ULT_KP+4,HCW_N+JT_Nw,HCH_N-R_N
			LSEL,NONE
			L,ULT_KP+3,ULT_KP+4
			CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+1,ULT_KP+2
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!BT_RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCW_N-R_N,-HCH_N
			K,ULT_KP+2,HCW_N,-HCH_N+R_N
			K,ULT_KP+3,HCW_N+JT_Nw,-HCH_N+R_N	
			!K,ULT_KP+4,HCW_N+JT_Nw,-HCH_N-JT_Nh+EXT_RAD		
			K,ULT_KP+5,HCW_N-R_N,-HCH_N-JT_Nh		
			!K,ULT_KP+6,HCW_N-R_N,-HCH_N-JT_Nh	
			K,ULT_KP+7,HCW_N-R_N,-HCH_N+R_N		
			!K,ULT_KP+8,HCW_N+JT_Nw-EXT_RAD,-HCH_N-JT_Nh+EXT_RAD
			LSEL,NONE
			!LARC,ULT_KP+4,ULT_KP+5,ULT_KP+8,EXT_RAD
			LARC,ULT_KP+3,ULT_KP+5,ULT_KP+7,EXT_RAD
			!L,ULT_KP+3,ULT_KP+4
			!L,ULT_KP+5,ULT_KP+6
			LESIZE,ALL,,,ARC_DIV
			CM,BRG_%THIS_COMP%_%THIS_REAL%,LINE
			!L,ULT_KP+6,ULT_KP+1
			
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+7,R_N
			LESIZE,ALL,,,ARC_DIV
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+5,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			! LESIZE,ALL,,,ARC_DIV
			! BOT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,-HCH_N
			K,ULT_KP+2,HCW_N-R_N,-HCH_N
			K,ULT_KP+3,HCW_N-R_N,-HCH_N-JT_Nh
			K,ULT_KP+4,,-HCH_N-JT_Nh
			LSEL,NONE
			L,ULT_KP+3,ULT_KP+4
			CM,BOT_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+1,ULT_KP+2
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+3
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
		*ENDIF	

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		! CMSEL,,TRG_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,BRG_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THAT_MAT,THIS_MAT
		ALLSEL,BELOW,AREA
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP

		ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
		ALLSEL,BELOW,AREA
		NUMMRG,NODE
		NUMMRG,KP
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		MSHKEY,1
		MSHAPE,0
		*IF,CABLE_TYPE(i,1),EQ,'RIS',THEN
			MSHKEY,0
			ESIZE,ELM_SZ*2 
		*ELSE
			ESIZE,ELM_SZ
		*ENDIF
		AMESH,ALL	
		CM,AREA_%THIS_COMP%_RGT,AREA

		LSEL,,LCCAT
		LDELE,ALL

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		ALLSEL,BELOW,AREA
		NUMMRG,NODE,1e-4
		NUMMRG,KP,1e-4
		ARSYM,X,ALL
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THAT_MAT,THIS_MAT
		ALLSEL,BELOW,AREA
		NUMMRG,NODE
		NUMMRG,KP

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		CMSEL,U,AREA_%THIS_COMP%_RGT
		ESLA,,1
		ESEL,R,ESYS,,THIS_CS+5
		EMODIF,ALL,ESYS,THIS_CS+8
		ESLA,,1
		ESEL,R,ESYS,,THIS_CS+6
		EMODIF,ALL,ESYS,THIS_CS+7
		ESLA,,1
		ESEL,R,ESYS,,THIS_CS+2
		EMODIF,ALL,ESYS,THIS_CS+4
		*ENDDO
	*ELSE
		*DO,k,1,NT_LOWF
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	!Jacket internal radius
		
		! Geometric parameters
		CHAM = 0.0
		! R(i,k) = JT_h(i,k)/2					 !Jacket internal radiusalls

		R_N = R(i,k)
		EXT_RAD = R_N+JT_h(i,k)       	 !Jacket external radius		
		ELM_SZ = JT_h(i,k)/4
		
		JH_N = JH(i,k)			!Half Jacket Height
		JW_N = 2*HJW(i,k)       !Half jacket width
		HCW_N = HCW(i,k)        !Half Conductor width
		HCH_N = HCH(i,k)        !Half Conductor Height
		JT_Nh = JT_h(i,k)
		JT_Nw = JT_w(i,k)

		LHI_N = LHI(i,k)
		LWI_N = LWI(i,k)

		! Local CS to identify cable centre and later define orthotropic material properties
		CSYS,MAX_CS+8*(NL_HIGHF*NT_HIGHF+NT_LOWF*(i-NL_HIGHF-1)+(k-1))+2

		THIS_REAL = 100+NL_HIGHF*NT_HIGHF+NT_LOWF*(i-NL_HIGHF-1)+k
		THIS_CS = MAX_CS+8*(NL_HIGHF*NT_HIGHF+NT_LOWF*(i-NL_HIGHF-1)+(k-1))

		! create jacket areas
		*IF,CABLE_TYPE(i,1),EQ,'RIS',THEN
			! TOP
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,HCH_N
			K,ULT_KP+2,HCH_N*cos(pi/4),HCH_N*sin(pi/4)
			K,ULT_KP+3,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+4,,HCH_N+JT_Nh
			K,ULT_KP+5,, 
			LSEL,NONE				
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+5,HCH_N
			*GET,ULT_LN,LINE,,NUM,MAX
			CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+3,ULT_KP+4
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3		
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!TP-RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCH_N*cos(pi/4),HCH_N*sin(pi/4)
			K,ULT_KP+2,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+3,HCW_N+JT_Nw,HCH_N-R_N
			K,ULT_KP+4,HCW_N+JT_Nw-EXT_RAD,HCH_N+JT_Nh-EXT_RAD			
			LSEL,NONE
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+1,ULT_KP+3
			LARC,ULT_KP+2,ULT_KP+3,ULT_KP+4,EXT_RAD
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			! LESIZE,ALL,,,ARC_DIV
			! RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCH_N*cos(pi/4),HCH_N*sin(pi/4)
			K,ULT_KP+2,HCW_N+JT_Nw,HCH_N+JT_Nh-EXT_RAD
			K,ULT_KP+3,HCW_N+JT_Nw,-(HCH_N+JT_Nh-EXT_RAD)
			K,ULT_KP+4,HCH_N*cos(pi/4),-HCH_N*sin(pi/4)
			K,ULT_KP+5,,,
			LSEL,NONE
			LARC,ULT_KP+1,ULT_KP+4,ULT_KP+5,HCH_N
			CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+2,ULT_KP+3
			L,ULT_KP+4,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!BT-RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCH_N*cos(pi/4),-HCH_N*sin(pi/4)
			K,ULT_KP+2,HCW_N-R_N,-HCH_N-JT_Nh
			K,ULT_KP+3,HCW_N+JT_Nw,-HCH_N+R_N
			K,ULT_KP+4,HCW_N+JT_Nw-EXT_RAD,-HCH_N-JT_Nh+EXT_RAD			
			LSEL,NONE
			L,ULT_KP+1,ULT_KP+2
			L,ULT_KP+1,ULT_KP+3
			LARC,ULT_KP+2,ULT_KP+3,ULT_KP+4,EXT_RAD
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			! BOT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,-HCH_N
			K,ULT_KP+2,HCH_N*cos(pi/4),-HCH_N*sin(pi/4)
			K,ULT_KP+3,HCW_N-R_N,-HCH_N-JT_Nh
			K,ULT_KP+4,,-HCH_N-JT_Nh
			K,ULT_KP+5,, 
			LSEL,NONE										
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+5,HCH_N
			*GET,ULT_LN,LINE,,NUM,MAX
			CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3
			L,ULT_KP+3,ULT_KP+4
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+3
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
		*ELSE
			! TOP
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,HCH_N
			K,ULT_KP+2,HCW_N-R_N,HCH_N
			K,ULT_KP+3,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+4,,HCH_N+JT_Nh
			LSEL,NONE
			L,ULT_KP+3,ULT_KP+4
			CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+1,ULT_KP+2
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!TP-RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCW_N-R_N,HCH_N
			K,ULT_KP+2,HCW_N,HCH_N-R_N
			K,ULT_KP+3,HCW_N+JT_Nw,HCH_N-R_N
			!K,ULT_KP+4,HCW_N+JT_Nw,HCH_N+JT_Nh-EXT_RAD
			K,ULT_KP+5,HCW_N-R_N,HCH_N+JT_Nh
			!K,ULT_KP+6,HCW_N-R_N,HCH_N+JT_Nh
			K,ULT_KP+7,HCW_N-R_N,HCH_N-R_N
			!K,ULT_KP+8,HCW_N+JT_Nw-EXT_RAD,HCH_N+JT_Nh-EXT_RAD
			LSEL,NONE
			! LARC,ULT_KP+4,ULT_KP+5,ULT_KP+8,EXT_RAD
			LARC,ULT_KP+3,ULT_KP+5,ULT_KP+7,EXT_RAD
			!L,ULT_KP+3,ULT_KP+4
			!L,ULT_KP+5,ULT_KP+6
			LESIZE,ALL,,,ARC_DIV
			CM,TRG_%THIS_COMP%_%THIS_REAL%,LINE
			! L,ULT_KP+6,ULT_KP+1
			
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+7,R_N
			LESIZE,ALL,,,ARC_DIV
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+5,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			! LESIZE,ALL,,,ARC_DIV
			! RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCW_N,HCH_N-R_N
			K,ULT_KP+2,HCW_N,-HCH_N+R_N
			K,ULT_KP+3,HCW_N+JT_Nw,-HCH_N+R_N
			K,ULT_KP+4,HCW_N+JT_Nw,HCH_N-R_N
			LSEL,NONE
			L,ULT_KP+3,ULT_KP+4
			CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+1,ULT_KP+2
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			!BT_RGT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,HCW_N-R_N,-HCH_N
			K,ULT_KP+2,HCW_N,-HCH_N+R_N
			K,ULT_KP+3,HCW_N+JT_Nw,-HCH_N+R_N	
			!K,ULT_KP+4,HCW_N+JT_Nw,-HCH_N-JT_Nh+EXT_RAD		
			K,ULT_KP+5,HCW_N-R_N,-HCH_N-JT_Nh		
			!K,ULT_KP+6,HCW_N-R_N,-HCH_N-JT_Nh	
			K,ULT_KP+7,HCW_N-R_N,-HCH_N+R_N		
			!K,ULT_KP+8,HCW_N+JT_Nw-EXT_RAD,-HCH_N-JT_Nh+EXT_RAD
			LSEL,NONE
			!LARC,ULT_KP+4,ULT_KP+5,ULT_KP+8,EXT_RAD
			LARC,ULT_KP+3,ULT_KP+5,ULT_KP+7,EXT_RAD
			!L,ULT_KP+3,ULT_KP+4
			!L,ULT_KP+5,ULT_KP+6
			LESIZE,ALL,,,ARC_DIV
			CM,BRG_%THIS_COMP%_%THIS_REAL%,LINE
			!L,ULT_KP+6,ULT_KP+1
			
			LARC,ULT_KP+1,ULT_KP+2,ULT_KP+7,R_N
			LESIZE,ALL,,,ARC_DIV
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+5,ULT_KP+1
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
			! LESIZE,ALL,,,ARC_DIV
			! BOT
			KSEL,ALL
			*GET,ULT_KP,KP,,NUM,MAX	
			KSEL,NONE
			K,ULT_KP+1,,-HCH_N
			K,ULT_KP+2,HCW_N-R_N,-HCH_N
			K,ULT_KP+3,HCW_N-R_N,-HCH_N-JT_Nh
			K,ULT_KP+4,,-HCH_N-JT_Nh
			LSEL,NONE
			L,ULT_KP+3,ULT_KP+4
			CM,BOT_%THIS_COMP%_%THIS_REAL%,LINE
			L,ULT_KP+4,ULT_KP+1
			L,ULT_KP+1,ULT_KP+2
			*GET,ULT_LN,LINE,,NUM,MAX	
			L,ULT_KP+2,ULT_KP+3
			ASEL,NONE
			AL,ALL
			AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+3
			LSEL,,LINE,,ULT_LN
			LATT,THIS_MAT,THIS_REAL
		*ENDIF	

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		! CMSEL,,TRG_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,BRG_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THAT_MAT,THIS_MAT
		ALLSEL,BELOW,AREA
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP

		ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
		ALLSEL,BELOW,AREA
		NUMMRG,NODE
		NUMMRG,KP
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		MSHKEY,1
		MSHAPE,0
		*IF,CABLE_TYPE(i,1),EQ,'RIS',THEN
			MSHKEY,0
			ESIZE,ELM_SZ*2 
		*ELSE
			ESIZE,ELM_SZ
		*ENDIF
		AMESH,ALL	
		CM,AREA_%THIS_COMP%_RGT,AREA

		LSEL,,LCCAT
		LDELE,ALL

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		ALLSEL,BELOW,AREA
		NUMMRG,NODE,1e-4
		NUMMRG,KP,1e-4
		ARSYM,X,ALL
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THAT_MAT,THIS_MAT
		ALLSEL,BELOW,AREA
		NUMMRG,NODE
		NUMMRG,KP

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		CMSEL,U,AREA_%THIS_COMP%_RGT
		ESLA,,1
		ESEL,R,ESYS,,THIS_CS+5
		EMODIF,ALL,ESYS,THIS_CS+8
		ESLA,,1
		ESEL,R,ESYS,,THIS_CS+6
		EMODIF,ALL,ESYS,THIS_CS+7
		ESLA,,1
		ESEL,R,ESYS,,THIS_CS+2
		EMODIF,ALL,ESYS,THIS_CS+4
		*ENDDO
	*ENDIF
*ENDDO

ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE
NUMMRG,KP