!=======================================================================
! TF_tins_RIS.f - Turn insulation of a round-in-square (RIS) WP. Called by STR_MODEL.f
! when WP_TOPOLOGY = RIS_only.
!=======================================================================
/PREP7
LSEL,,LCCAT
LDELE,ALL
ALLSEL,ALL,ALL
NUMCMP,LINE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! TURN INSULATION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
THIS_COMP = 'TINS'
THIS_MAT = TINS_MAT
THAT_MAT = JCK_MAT
THIS_ET = TINS_ET
! ELM_SZ = ICIT
! CHAM_DIV = 4
! CHAM_SD_DIV = (ARC_DIV-CHAM_DIV)/2

*DO,i,1,GRADES
	*IF,i,LE,NL_HIGHF,THEN
		*DO,k,1,NT_HIGHF
		KSEL,ALL
		LSEL,ALL
		NUMCMP,KP
		NUMCMP,LINE
		*GET,ULT_KP,KP,,NUM,MAX		
		! Geometric parameters
		THICK = ICIT
		! R(i,k) = JT_h(i,k)/2			!Jacket internal radius
		R_N = R(i,k)	
		IN_RAD = R_N!+JT_h(i,k)       	!Jacket external radius		
		EXT_RAD = IN_RAD+THICK
		ELM_SZ = .001!JT_h(i,k)/5
		
		JH_N = JH(i,k)			!Half Jacket Height
		JW_N = HJW(i,k)       !Half jacket width
		HCW_N = HCW(i,k)        !Half Conductor width
		HCH_N = HCH(i,k)        !Half Conductor Height
		JT_Nh = JT_h(i,k)
		JT_Nw = JT_w(i,k)

		LHI_N = LHI(i,k)
		LWI_N = LWI(i,k)

		! Local CS to identify cable centre and later define orthotropic material properties
		CSYS,MAX_CS+8*((k-1)+NT_HIGHF*(i-1))+2

		THIS_REAL = 100+NT_HIGHF*(i-1)+k
		THIS_CS = MAX_CS+8*((k-1)+NT_HIGHF*(i-1))

		! create turn insulation areas
		! TOP
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,HCH_N+JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,HCH_N+JT_Nh
		K,ULT_KP+3,JW_N-IN_RAD,HCH_N+JT_Nh+THICK
		K,ULT_KP+4,0.0,HCH_N+JT_Nh+THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,HCH_N+JT_Nh
		K,ULT_KP+2,-(JW_N-IN_RAD),HCH_N+JT_Nh
		K,ULT_KP+3,-(JW_N-IN_RAD),HCH_N+JT_Nh+THICK
		K,ULT_KP+4,0.0,HCH_N+JT_Nh+THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL

		!TP-RGT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N-IN_RAD,HCH_N+JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,HCH_N+JT_Nh+THICK
		K,ULT_KP+3,JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,JW_N+THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+5,JW_N-IN_RAD,HCH_N+JT_Nh-IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL

		! RGT
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+2,JW_N,0
		K,ULT_KP+3,JW_N+THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,JW_N+THICK,0
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N,0
		K,ULT_KP+2,JW_N,-(HCH_N+JT_Nh-IN_RAD)
		K,ULT_KP+3,JW_N+THICK,0
		K,ULT_KP+4,JW_N+THICK,-(HCH_N+JT_Nh-IN_RAD)
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL

		!BT_RGT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N-IN_RAD,-HCH_N-JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,-HCH_N-JT_Nh-THICK
		K,ULT_KP+3,JW_N,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+4,JW_N+THICK,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+5,JW_N-IN_RAD,-HCH_N-JT_Nh+IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+6
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL

		! BOT
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,-HCH_N-JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,-HCH_N-JT_Nh
		K,ULT_KP+3,JW_N-IN_RAD,-HCH_N-JT_Nh-THICK
		K,ULT_KP+4,0.0,-HCH_N-JT_Nh-THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,-HCH_N-JT_Nh
		K,ULT_KP+2,-(JW_N-IN_RAD),-HCH_N-JT_Nh
		K,ULT_KP+3,-(JW_N-IN_RAD),-HCH_N-JT_Nh-THICK
		K,ULT_KP+4,0.0,-HCH_N-JT_Nh-THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
				
		!BT_LFT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N+IN_RAD,-HCH_N-JT_Nh
		K,ULT_KP+2,-JW_N+IN_RAD,-HCH_N-JT_Nh-THICK
		K,ULT_KP+3,-JW_N,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+4,-JW_N-THICK,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+5,-JW_N+IN_RAD,-HCH_N-JT_Nh+IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+7
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL
		
		! LFT
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+2,-JW_N,0
		K,ULT_KP+3,-JW_N-THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,-JW_N-THICK,0
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+4
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N,0
		K,ULT_KP+2,-JW_N,-(HCH_N+JT_Nh-IN_RAD)
		K,ULT_KP+3,-JW_N-THICK,0
		K,ULT_KP+4,-JW_N-THICK,-(HCH_N+JT_Nh-IN_RAD)
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+4
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		!TP-RGT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N+IN_RAD,HCH_N+JT_Nh
		K,ULT_KP+2,-JW_N+IN_RAD,HCH_N+JT_Nh+THICK
		K,ULT_KP+3,-JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,-JW_N-THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+5,-JW_N+IN_RAD,HCH_N+JT_Nh-IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+8
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THAT_MAT,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		ALLSEL,BELOW,AREA
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		! CMSEL,,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,BRGi_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,BRGe_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		ALLSEL,BELOW,AREA
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL	
		CM,AREA_%THIS_COMP%_RGT,AREA

		LSEL,,LCCAT
		LDELE,ALL
		*ENDDO
	*ELSE
		*DO,k,1,NT_LOWF
		KSEL,ALL
		LSEL,ALL
		NUMCMP,KP
		NUMCMP,LINE
		*GET,ULT_KP,KP,,NUM,MAX		
			! Geometric parameters
		THICK = ICIT
		! R(i,k) = JT_h(i,k)/2			!Jacket internal radius
		R_N = R(i,k)	
		IN_RAD = R_N!+JT_h(i,k)       	!Jacket external radius		
		EXT_RAD = IN_RAD+THICK
		ELM_SZ = 0.001! JT_h(i,k)/5
		
		JH_N = JH(i,k)			!Half Jacket Height
		JW_N =  HJW(i,k)       !Half jacket width
		HCW_N = HCW(i,k)        !Half Conductor width
		HCH_N = HCH(i,k)        !Half Conductor Height
		JT_Nh = JT_h(i,k)
		JT_Nw = JT_w(i,k)

		LHI_N = LHI(i,k)
		LWI_N = LWI(i,k)

		! local CS to identify cable centre and later define orthotropic material properties
		CSYS,MAX_CS+8*(NL_HIGHF*NT_HIGHF+NT_LOWF*(i-NL_HIGHF-1)+(k-1))+2

		THIS_REAL = 100+NL_HIGHF*NT_HIGHF+NT_LOWF*(i-NL_HIGHF-1)+k
		THIS_CS = MAX_CS+8*(NL_HIGHF*NT_HIGHF+NT_LOWF*(i-NL_HIGHF-1)+(k-1))

		! create turn insulation areas
		! TOP
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,HCH_N+JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,HCH_N+JT_Nh
		K,ULT_KP+3,JW_N-IN_RAD,HCH_N+JT_Nh+THICK
		K,ULT_KP+4,0.0,HCH_N+JT_Nh+THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,HCH_N+JT_Nh
		K,ULT_KP+2,-(JW_N-IN_RAD),HCH_N+JT_Nh
		K,ULT_KP+3,-(JW_N-IN_RAD),HCH_N+JT_Nh+THICK
		K,ULT_KP+4,0.0,HCH_N+JT_Nh+THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL

		!TP-RGT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N-IN_RAD,HCH_N+JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,HCH_N+JT_Nh+THICK
		K,ULT_KP+3,JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,JW_N+THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+5,JW_N-IN_RAD,HCH_N+JT_Nh-IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+5
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL

		! RGT
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+2,JW_N,0
		K,ULT_KP+3,JW_N+THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,JW_N+THICK,0
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N,0
		K,ULT_KP+2,JW_N,-(HCH_N+JT_Nh-IN_RAD)
		K,ULT_KP+3,JW_N+THICK,0
		K,ULT_KP+4,JW_N+THICK,-(HCH_N+JT_Nh-IN_RAD)
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+2
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL

		!BT_RGT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,JW_N-IN_RAD,-HCH_N-JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,-HCH_N-JT_Nh-THICK
		K,ULT_KP+3,JW_N,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+4,JW_N+THICK,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+5,JW_N-IN_RAD,-HCH_N-JT_Nh+IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+6
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL

		! BOT
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,-HCH_N-JT_Nh
		K,ULT_KP+2,JW_N-IN_RAD,-HCH_N-JT_Nh
		K,ULT_KP+3,JW_N-IN_RAD,-HCH_N-JT_Nh-THICK
		K,ULT_KP+4,0.0,-HCH_N-JT_Nh-THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,0.0,-HCH_N-JT_Nh
		K,ULT_KP+2,-(JW_N-IN_RAD),-HCH_N-JT_Nh
		K,ULT_KP+3,-(JW_N-IN_RAD),-HCH_N-JT_Nh-THICK
		K,ULT_KP+4,0.0,-HCH_N-JT_Nh-THICK
		LSEL,NONE
		L,ULT_KP+3,ULT_KP+4
		CM,TOP_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+4,ULT_KP+1
		L,ULT_KP+1,ULT_KP+2
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+3
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+1
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
				
		!BT_LFT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N+IN_RAD,-HCH_N-JT_Nh
		K,ULT_KP+2,-JW_N+IN_RAD,-HCH_N-JT_Nh-THICK
		K,ULT_KP+3,-JW_N,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+4,-JW_N-THICK,-HCH_N-JT_Nh+IN_RAD
		K,ULT_KP+5,-JW_N+IN_RAD,-HCH_N-JT_Nh+IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+7
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL
		
		! LFT
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+2,-JW_N,0
		K,ULT_KP+3,-JW_N-THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,-JW_N-THICK,0
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+4
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		KSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N,0
		K,ULT_KP+2,-JW_N,-(HCH_N+JT_Nh-IN_RAD)
		K,ULT_KP+3,-JW_N-THICK,0
		K,ULT_KP+4,-JW_N-THICK,-(HCH_N+JT_Nh-IN_RAD)
		LSEL,NONE
		L,ULT_KP+1,ULT_KP+2
		CM,RGT_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+3,ULT_KP+4
		L,ULT_KP+1,ULT_KP+3
		*GET,ULT_LN,LINE,,NUM,MAX	
		L,ULT_KP+2,ULT_KP+4
		ASEL,NONE
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+4
		LSEL,,LINE,,ULT_LN
		LATT,THIS_MAT,THIS_REAL
		
		!TP-RGT
		KSEL,ALL
		LSEL,ALL
		*GET,ULT_KP,KP,,NUM,MAX	
		KSEL,NONE
		K,ULT_KP+1,-JW_N+IN_RAD,HCH_N+JT_Nh
		K,ULT_KP+2,-JW_N+IN_RAD,HCH_N+JT_Nh+THICK
		K,ULT_KP+3,-JW_N,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+4,-JW_N-THICK,HCH_N+JT_Nh-IN_RAD
		K,ULT_KP+5,-JW_N+IN_RAD,HCH_N+JT_Nh-IN_RAD
		*GET,ULT_LN,LINE,,NUM,MAX
		LSEL,NONE
		LARC,ULT_KP+1,ULT_KP+3,ULT_KP+5,IN_RAD
		CM,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		L,ULT_KP+1,ULT_KP+2
		L,ULT_KP+3,ULT_KP+4		
		LSEL,NONE
		LARC,ULT_KP+2,ULT_KP+4,ULT_KP+5,EXT_RAD
		CM,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		ASEL,NONE
		LSEL,A,LINE,,ULT_LN+1,ULT_LN+3
		AL,ALL
		AATT,THIS_MAT,THIS_REAL,THIS_ET,THIS_CS+8
		LSEL,S,LINE,,ULT_LN+4
		LATT,THIS_MAT,THIS_REAL

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THAT_MAT,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		ALLSEL,BELOW,AREA
		KSLL,,1
		NSLL,,1
		NUMMRG,NODE
		NUMMRG,KP
		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		! CMSEL,,TRGi_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,TRGe_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,BRGi_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL
		! CMSEL,,BRGe_%THIS_COMP%_%THIS_REAL%,LINE
		! LCCAT,ALL

		ASEL,,REAL,,THIS_REAL
		ASEL,R,MAT,,THIS_MAT
		ASEL,R,LOC,X,-LTOT/2,LTOT/2
		ALLSEL,BELOW,AREA
		MSHKEY,1
		MSHAPE,0
		ESIZE,ELM_SZ
		AMESH,ALL	
		CM,AREA_%THIS_COMP%_RGT,AREA

		LSEL,,LCCAT
		LDELE,ALL
		*ENDDO
	*ENDIF
*ENDDO

ASEL,,MAT,,THAT_MAT,THIS_MAT,,1
ALLSEL,BELOW,AREA
NUMMRG,NODE
NUMMRG,KP
