!-----------------------------------------------------------------------!
! Auto-generated by export_ansys_input.m from MATLAB design point "WP_TF_input_template_1"
! Source: search/scan_wp_designs.m DATA row, n_layers=11, Iop=48009.0 A
! Review OUTERLEG_INTR and AIR_HEIGHT below: this 2D nose solver has no
! equivalent quantity for them, they are left at template defaults.
! Conductor shape: rect (shape_cable = 201).
!-----------------------------------------------------------------------!
/PREP7
SCALEV = 1.0
SCALEE = 1.0
SCALED = 1.0

SI_UNIT = 1			  ! set = 1 to use SI units [ 1 = m -- 0 = mm]
*IF,SI_UNIT,EQ,0,THEN
	SCALEV = 1E3
	SCALEE = 1E-6
	SCALED = 1E-9
*ENDIF

WEDGE = 1   			  ! set =1 to draw 2 half-WP sections and model wedge contact, =0 to draw one half-WP section only
DEV = -0.0*1.E-3**SI_UNIT ! Jacket external radius deviation from the nominal value
pi = acos(-1)

HOT = 0                     ! [0 = 4.5 K - 1 = 293 K]
SCALEF = 1.0	
DELTA_SS = 10.38E-6*(293-4) ! 316LN
*IF,HOT,EQ,1,THEN
	SCALEF = 1.0+10.38E-6*(293-4)
*ENDIF
!-----------------------------------------------------------------------!
N_TF = 12 				! number of TF magnets
ANG_DIV = 360/N_TF 		! angular separation of TF magnets
AIR_HEIGHT = 2.0*(2670.00*1.E-3**SI_UNIT)	! FEM-only, not derived from MATLAB - review
!-----------------------------------------------------------------------!
SL_LENGTH = 1 ! out-of-plane depth [m]: results do not depend on it unless moments act on the GPS
!-----------------------------------------------------------------------!
WP_TOPOLOGY = 'standard'

GRADES = 5

*DIM,NT,ARRAY,GRADES,1
NT(1,1)  =  14
NT(2,1)  =  14
NT(3,1)  =  12
NT(4,1)  =  12
NT(5,1)  =  10

*DIM,NL,ARRAY,GRADES,1
NL(1,1)  =  4
NL(2,1)  =  1
NL(3,1)  =  2
NL(4,1)  =  3
NL(5,1)  =  1

*VOPER,NSPR,NL,MULT,NT
*VSCFUN,N_WIRES,SUM,NSPR

*VSCFUN,NL_TOT,SUM,NL

DLR = 5.0                 ! number of double - layers ---- DPC if double-pancakes
DPC = DLR

*DIM,LAYOUT,CHAR,3
LAYOUT(1) = 'DP'
LAYOUT(2) = 'DL'
LAYOUT(3) = 'LW'		! Layer Wound

DESIGN = LAYOUT(3)

ICIT = SCALEF*1*1.E-3**SI_UNIT    !Inter Conductor Insulation Thickness
GIT = SCALEF*5*1.E-3**SI_UNIT     !Ground insulation thickness
CASE_GIT = SCALEF*0.0*1.E-3**SI_UNIT

BUFF = SCALEF*0.0*1.E-3**SI_UNIT			! Insertion gap
INTLT = SCALEF*0.0*1.E-3**SI_UNIT

WP_GIT = SCALEF*5*1.E-3**SI_UNIT
DPIT = SCALEF*0
DLIT = DPIT							!Double layers insulation thickness
LWIT = SCALEF*0.5*1.E-3**SI_UNIT	!Layer wound insulation thickness
CFR = SCALEF*3.5*1.E-3**SI_UNIT       !Cable Fillet Radius = jacket internal radius

TF_CURRENT = -48009.0

!-----------------------------------------------------------------------!
!!! ARRAY DEFINITION
!-----------------------------------------------------------------------!
NT_G = NT(1)
*VSCFUN,NL_G,SUM,NL

*DIM,CSYS_CABLE,ARRAY,NL_G,NT_G
*DIM,JT_h,ARRAY,NL_G,NT_G
*DIM,JT_w,ARRAY,NL_G,NT_G
*DIM,JH,ARRAY,NL_G,NT_G
*DIM,JW,ARRAY,NL_G,NT_G
*DIM,DPTH,ARRAY,NL_G,NT_G
*DIM,HCH,ARRAY,NL_G,NT_G
*DIM,HCW,ARRAY,NL_G,NT_G
*DIM,HCL,ARRAY,NL_G,NT_G
*DIM,HJH,ARRAY,NL_G,NT_G
*DIM,HJW,ARRAY,NL_G,NT_G
*DIM,JIR,ARRAY,NL_G,NT_G
*DIM,JER,ARRAY,NL_G,NT_G
*DIM,LHI,ARRAY,NL_G,NT_G
*DIM,LWI,ARRAY,NL_G,NT_G
*DIM,R,ARRAY,NL_G,NT_G
*DIM,dJR,ARRAY,NL_G,NT_G
*DIM,GIR,ARRAY,NL_G,NT_G
*DIM,CABLE_TYPE,CHAR,GRADES,1
*DIM,JHG,ARRAY, GRADES,1
*DIM,JT_hG,ARRAY, GRADES,1
*DIM,JT_wG,ARRAY, GRADES,1
!-----------------------------------------------------------------------!
!!! Parameters
!-----------------------------------------------------------------------!
!!! Cable Type
CABLE_TYPE(1,1)  = 'rect'
CABLE_TYPE(2,1)  = 'rect'
CABLE_TYPE(3,1)  = 'rect'
CABLE_TYPE(4,1)  = 'rect'
CABLE_TYPE(5,1)  = 'rect'

!!! Conductor Width (Insulated)
LTOT = SCALEF*(38.8596)*1.E-3**SI_UNIT

!!! Non insulated cable Height LOOK -ICIT*2 [m]
JHG(1,1) = SCALEF*(28.3275)*1.E-3**SI_UNIT-ICIT*2
JHG(2,1) = SCALEF*(24.2731)*1.E-3**SI_UNIT-ICIT*2
JHG(3,1) = SCALEF*(24.2731)*1.E-3**SI_UNIT-ICIT*2
JHG(4,1) = SCALEF*(25.0069)*1.E-3**SI_UNIT-ICIT*2
JHG(5,1) = SCALEF*(25.0069)*1.E-3**SI_UNIT-ICIT*2

n=0
*DO,i,1,GRADES
	*DO,j,1,NL(i)
	n=n+1
		*DO,k,1,NT(i)
			JH(n,k) = JHG(i,1)
		*ENDDO
	*ENDDO
*ENDDO
!-----------------------------------------------------------------------!
!!! Jacket Thickness [m]
JT_wG(1,1)    = SCALEF*(2.3)*1.E-3**SI_UNIT
JT_wG(2,1)    = SCALEF*(2.8)*1.E-3**SI_UNIT
JT_wG(3,1)    = SCALEF*(2.8)*1.E-3**SI_UNIT
JT_wG(4,1)    = SCALEF*(3.5)*1.E-3**SI_UNIT
JT_wG(5,1)    = SCALEF*(3.5)*1.E-3**SI_UNIT
JT_hG(1,1)   = JT_wG(1,1)
JT_hG(2,1)   = JT_wG(2,1)
JT_hG(3,1)   = JT_wG(3,1)
JT_hG(4,1)   = JT_wG(4,1)
JT_hG(5,1)   = JT_wG(5,1)
!-----------------------------------------------------------------------!
n=0
*DO,i,1,GRADES
	*DO,j,1,NL(i)
		n=n+1
		*DO,k,1,NT(i)
			JT_h(n,k)= JT_hG(i,1)
			JT_w(n,k)= JT_wG(i,1)
		*ENDDO
	*ENDDO
*ENDDO
!-----------------------------------------------------------------------!
*DIM,H_GRADES,ARRAY,GRADES,1
*DO,i,1,GRADES
	H_GRADES(i)=(JHG(i,1)+2*ICIT)*NL(i)
*ENDDO
*VSCFUN,WPH,SUM,H_GRADES
WPH = WPH+(NL_TOT-1)*LWIT+2*GIT+2*BUFF  		!WP HEIGHT

WPW_HIGHF = LTOT*NT(1)+2*DLIT
WPW_LOWF = LTOT*NT(GRADES)+2*DLIT

*DIM,W_GRADES,ARRAY,GRADES,1
*DO,i,1,GRADES
	W_GRADES(i)=LTOT*NT(i)
*ENDDO

!!! GROUND INSULATION PARAMETERS
INCL = ANG_DIV/2
RAD1 = LTOT*0.8-BUFF-GIT-DLIT     ! Radius of the DL insulation corner
!-----------------------------------------------------------------------!	
!!! CASE DIMENSION 
CASE_THICK = SCALEF*20*1.E-3**SI_UNIT
Ri_ = SCALEF*(1.25943*1e3)*1.E-3**SI_UNIT
Rj_ = Ri_-CASE_THICK-WPH
Rk_ = SCALEF*(0.761409*1e3)*1.E-3**SI_UNIT

INNLEG_INTR = Rk_
INNLEG_OUTR = Ri_
Rm_INNERLEG = (INNLEG_INTR+INNLEG_OUTR)/2

OUTERLEG_INTR = SCALEF*(4.8*1e3)*1.E-3**SI_UNIT	! FEM-only, not derived from MATLAB - review
OUTERLEG_OUTR = OUTERLEG_INTR+WPH
Rm_OUTERLEG = (OUTERLEG_INTR+OUTERLEG_OUTR)/2

CASE_INS = SCALEF*1.5*1.E-3**SI_UNIT

*AFUN,DEG 
	CASEW_UP = Ri_*TAN(INCL)*2
	CASEW_LOW = Rk_*TAN(INCL)*2

	CASE_WIDTH = CASEW_UP-2*CASE_INS 
	CASE_WIDTH_LOW = CASEW_LOW-2*CASE_INS 

	CASE_HEIGHT = Ri_-Rk_

	WEDGE_OUTR = sqrt(Ri_**2+(CASE_WIDTH/2)**2)
	WEDGE_INTR = sqrt(Rk_**2+(CASE_WIDTH_LOW/2)**2)

	WEDGE_OUTR_INS = sqrt(Ri_**2+(CASEW_UP/2)**2)
	WEDGE_INTR_INS = sqrt(Rk_**2+(CASEW_LOW/2)**2)
*AFUN,RAD 

ANG_OUTR = INCL
PLASMA_FACE_FLAT_WIDTH = CASE_WIDTH
STRAIGHT_CASE_HEIGHT = SCALEF*0.0*1.E-3**SI_UNIT
PLASMA_FACE_EDGE_Y = WEDGE_OUTR*cos(ANG_DIV/2*pi/180)+STRAIGHT_CASE_HEIGHT
CASE_FLAT = SCALEF*1-20.0*1.E-3**SI_UNIT/CASE_THICK
NOSE = Rj_-Rk_  
ARC_NOSE = SCALEF*0

WP_INTR = INNLEG_INTR+NOSE

ZOFFST = 0.0
REF_CS = 0
REF_CS_SYMM = 0
SYMM_PLANE = 0

ULT_KP = 0
ULT_LN = 0 
ULT_AREA = 0

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
CAB_MAT     = 1
CAB_ET      = 1
CAB_ET_3D   = 101
JCK_MAT     = 2
JCK_ET      = 2
JCK_ET_3D   = 102
TINS_MAT    = 3
TINS_ET     = 3
TINS_ET_3D  = 103
FILL_MAT    = 4
FILL_ET     = 4
FILL_ET_3D  = 104
DPINS_MAT   = 5
DPINS_ET    = 5
DPINS_ET_3D = 105
GINS_MAT_VT = 7
GINS_MAT_HZ = 8
GINS_ET     = 7
GINS_ET_3D  = 107
BUFF_MAT_VT = 7
BUFF_MAT_HZ = 8
BUFF_ET     = 8
BUFF_ET_3D  = 108
WINS_MAT    = 9
WINS_ET     = 9
WINS_ET_3D  = 109
CASE_MAT_INN    = 10
CASE_ET_INN     = 10
CASE_ET_INN_3D  = 110
SBP_MAT     = 11
SBP_ET      = 11
SBP_ET_3D   = 111
CASE_MAT_OUT    = 12
CASE_ET_OUT     = 12
CASE_ET_OUT_3D  = 112
OIS_MAT     = 13
OIS_ET      = 13
OIS_ET_3D   = 113
PF_MAT     = 14
PF_ET      = 14
PF_ET_3D   = 114
SPB_MAT     = 15
SPB_ET      = 15
SPB_ET_3D   = 115
SPACER_MAT     = 16
SPACER_ET      = 16
SPACER_ET_3D   = 116
IISINS_MAT    = 17
IISINS_ET     = 17
IISINS_ET_3D  = 117
PLATE1_MAT    = 18
PLATE1_ET     = 18
PLATE1_ET_3D  = 118
PLATE2_MAT    = 19
PLATE2_ET     = 19
PLATE2_ET_3D  = 119
AIR_MAT     = 20
AIR_ET      = 20
AIR_ET_3D   = 120
PF_PLATE_MAT     = 21
PF_PLATE_ET      = 21
PF_PLATE_ET_3D   = 121
PF_TOP_MAT     = 22
PF_TOP_ET      = 22
PF_TOP_ET_3D   = 122
CS_SUP_MAT     = 23
CS_SUP_ET      = 23
CS_SUP_ET_3D   = 123
OMO_MAT     = 30
OMO_ET 	    = 30
OMO_ET_3D   = 130
PF_ET = 31
PF_ET_3D = 131
PF_COIL_MAT = 300
CS_ET = 32
CS_ET_3D = 132
CS_MODULES_MAT = 200
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
