%% main_WP_TF_design.m
% Generic entry point for the TF winding-pack (WP) design-point solver.
%
% Pipeline:
%   1. Ask for (and let you review) the machine input Excel file.
%   2. Read it into a parameter struct (io/read_machine_input.m).
%   3. Derive operating parameters and the WP envelope (physics/*.m).
%   4. Scan every turns/layers/case-wedge combination and keep every
%      design point that satisfies the geometric and Tresca stress checks
%      (search/*.m).
%   5. Save the full results table (.xlsx + a .mat companion for exact
%      reload), then let you browse every feasible design point, choose
%      one, plot its population scatter and its WP+Case cross-section, and
%      optionally export it as an ANSYS input file for FEM verification
%      (postprocess/*.m).
%
% To design a different machine, do NOT edit this file: copy
% input/WP_TF_input_template.xlsx to a new file (e.g.
% input/WP_TF_input_CEFTR.xlsx), edit its parameters, and point this
% script at it when asked.
%
% To revisit a saved design point later without re-running the scan, or to
% preview a manually edited "what-if" WP configuration, see
% postprocess/load_design_point.m and postprocess/plot_wp_section_manual_example.m.

clearvars; close all; clc

this_dir = fileparts(mfilename('fullpath'));
addpath(genpath(this_dir));

default_input = fullfile(this_dir, 'input', 'WP_TF_input_template.xlsx');

%% 1. Select and review the input file
fprintf('Machine input file [%s]:\n', default_input);
input_answer = strtrim(input('Press Enter to use it, or type another path: ', 's'));
if isempty(input_answer)
    input_file = default_input;
else
    input_file = input_answer;
end

fprintf(['\nBEFORE RUNNING: open %s and review every parameter\n' ...
    '(especially "Machine geometry" and "Design point") - this run will use\n' ...
    'exactly what is saved in that file.\n'], input_file);
proceed = strtrim(input('Type "y" to confirm and run the solver: ', 's'));
if ~strcmpi(proceed, 'y')
    fprintf('Aborted: input not confirmed.\n');
    return
end

[~, tag] = fileparts(input_file); % used to tag every output file from this run

%% 2-4. Read input, derive parameters, scan the design space
p = read_machine_input(input_file);
g = compute_operating_params(p);
env = wp_envelope(p, g);
combT = generate_combinations(env);

fprintf('\nScanning the design space (this can take a while)...\n');
DATA = scan_wp_designs(p, g, env, combT);

if height(DATA) == 0
    error('main_WP_TF_design:no_feasible_design', ...
        ['No feasible design point found for %s.\n' ...
         'Widen the "Numerical settings" (Iop_min/max, min/max_size_CICC, ' ...
         'WP_radial_build_max_est, ...) or review the machine geometry.'], input_file);
end

%% 5. Save all results, then browse and pick one
run_stamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
results_file = sprintf('%s_results_%s.xlsx', tag, run_stamp);
writetable(DATA, results_file);
% .mat companion (same base name): exact round-trip of DATA and p for
% LOAD_DESIGN_POINT, since a plain xlsx re-read cannot reconstruct the
% array-valued columns (n_turns, Cond_w, ...) on its own.
save(sprintf('%s_results_%s.mat', tag, run_stamp), 'DATA', 'p');
fprintf('\n%d feasible design point(s) saved to %s (+ .mat companion)\n', height(DATA), results_file);

sel_idx = browse_solutions(DATA);
plot_solution(DATA, sel_idx, tag);
plot_wp_section(DATA(sel_idx,:), p, sprintf('%s - design #%d', tag, sel_idx));
plot_wp_section_bfield(DATA(sel_idx,:), p, sprintf('%s - design #%d', tag, sel_idx));
plot_wp_diagnostics(DATA(sel_idx,:), p, sprintf('%s - design #%d', tag, sel_idx));

%% 6. Optional: export the chosen design point as an ANSYS APDL input file
export_answer = strtrim(input('Export this design point as an ANSYS input file for FEM verification? [y/N]: ', 's'));
if strcmpi(export_answer, 'y')
    export_ansys_input(DATA(sel_idx,:), p, pwd, sprintf('%s_%d', tag, sel_idx));
end

fprintf(['\nTo revisit this design point later without re-running the scan:\n' ...
    '  [row, p] = load_design_point(''%s'', %d);\n' ...
    '  plot_wp_section(row, p);\n' ...
    'For a manual "what-if" configuration (no Excel), see\n' ...
    'postprocess/plot_wp_section_manual_example.m.\n'], results_file, sel_idx);
