%% main_WP_TF_design.m
% Generic entry point for the TF winding-pack (WP) design-point solver.
%
% Pipeline:
%   1. Ask for (and let you review) the machine input Excel file.
%   2. Read it into a parameter struct (io/read_machine_input.m).
%   3. Derive operating parameters and the WP envelope (physics/*.m).
%   4. Scan every turns/layers/case-wedge combination and keep every
%      design point that satisfies the geometric and Tresca stress checks
%      (search/*.m).
%   5. Save the full results table (.xlsx + a .mat companion for exact
%      reload), then let you browse every feasible design point, choose
%      one, plot its population scatter and its WP+Case cross-section,
%      optionally verify it with the 2D FE mechanical surrogate
%      (physics/wp_mech_surrogate.m), run the 3D steps (coil shape and
%      field; beam + shell global model of the TF system with the coupled
%      sizing of the design, coil3d/ and search/couple_global_sizing.m)
%      and export it as an ANSYS input file for FEM verification
%      (postprocess/*.m).
%
% To design a different machine, do NOT edit this file: copy
% input/WP_TF_input_template.xlsx to a new file (e.g.
% input/WP_TF_input_CEFTR.xlsx), edit its parameters, and point this
% script at it when asked.
%
% To revisit a saved design point later without re-running the scan, or to
% preview a manually edited "what-if" WP configuration, see
% postprocess/load_design_point.m and postprocess/plot_wp_section_manual_example.m.

clearvars; close all; clc

this_dir = fileparts(mfilename('fullpath'));
addpath(genpath(this_dir));
rmpath(genpath(fullfile(this_dir, 'legacy')));   % old scripts and functions, not used by the pipeline

default_input = fullfile(this_dir, 'input', 'WP_TF_input_template.xlsx');

%% 1. Select and review the input file
fprintf('Machine input file [%s]:\n', default_input);
input_answer = strtrim(input('Press Enter to use it, or type another path: ', 's'));
if isempty(input_answer)
    input_file = default_input;
else
    input_file = input_answer;
end

fprintf(['\nBEFORE RUNNING: open %s and review every parameter\n' ...
    '(especially "Machine geometry" and "Design point") - this run will use\n' ...
    'exactly what is saved in that file.\n'], input_file);
proceed = strtrim(input('Type "y" to confirm and run the solver: ', 's'));
if ~strcmpi(proceed, 'y')
    fprintf('Aborted: input not confirmed.\n');
    return
end

[~, tag] = fileparts(input_file); % used to tag every output file from this run

%% 2-4. Read input, derive parameters, scan the design space
p = read_machine_input(input_file);
g = compute_operating_params(p);
env = wp_envelope(p, g);
combT = generate_combinations(env);

fprintf('\nScanning the design space (this can take a while)...\n');
[DATA, field_cal] = scan_wp_designs(p, g, env, combT);
if ~isempty(field_cal)
    plot_field_calibration(field_cal, p, tag);   % peak factor k(W, Iop) and layer profile used by the scan
end

if height(DATA) == 0
    error('main_WP_TF_design:no_feasible_design', ...
        ['No feasible design point found for %s.\n' ...
         'Widen the "Numerical settings" (Iop_min/max, min/max_size_CICC, ' ...
         'WP_radial_build_max_est, ...) or review the machine geometry.'], input_file);
end

%% 5. Save all results, then browse and pick one
run_stamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
results_file = sprintf('%s_results_%s.xlsx', tag, run_stamp);
writetable(DATA, results_file);
% .mat companion (same base name): exact round-trip of DATA and p for
% LOAD_DESIGN_POINT, since a plain xlsx re-read cannot reconstruct the
% array-valued columns (n_turns, Cond_w, ...) on its own.
save(sprintf('%s_results_%s.mat', tag, run_stamp), 'DATA', 'p', 'field_cal');
fprintf('\n%d feasible design point(s) saved to %s (+ .mat companion)\n', height(DATA), results_file);

sel_idx = browse_solutions(DATA);
plot_solution(DATA, sel_idx, tag);
plot_wp_section(DATA(sel_idx,:), p, sprintf('%s - design #%d', tag, sel_idx));
plot_wp_section_bfield(DATA(sel_idx,:), p, sprintf('%s - design #%d', tag, sel_idx));
plot_wp_diagnostics(DATA(sel_idx,:), p, sprintf('%s - design #%d', tag, sel_idx));
plot_hotspot_transient(DATA(sel_idx,:), p, sprintf('%s - design #%d - hot spot', tag, sel_idx));

%% 5b. Optional: 2D FE mechanical verification of the chosen design point
% Solves the true equilibrium of the inner-leg section (rounded turns,
% contacts with friction, Lorentz + cool-down + axial load), validated
% against ANSYS; reports the primary-stress figure of merit (Pm <= Sm,
% Pm+Pb <= 1.5 Sm on jacket walls and case SCLs) and the fillet peak.
mech_answer = strtrim(input('Run the 2D FE mechanical surrogate on this design (about a minute)? [y/N]: ', 's'));
if strcmpi(mech_answer, 'y')
    mech = wp_mech_surrogate(DATA(sel_idx,:), p);
    [mech_fig, mech_gps_fig] = plot_wp_mech_surrogate(mech, p, sprintf('%s - design #%d', tag, sel_idx));
    mech_zoom_fig = plot_conductor_zoom(mech, 1, sprintf('%s - design #%d - turn 1 mesh', tag, sel_idx));
    if ~mech.valid
        fprintf(2, ['The mechanical verification is NOT valid (%s): do not use its figure ' ...
            'of merit; check the mesh/contact settings or run the FEM.\n'], mech.checks.summary);
    elseif ~mech.fom.ok && isfield(p, 'scf_model') && p.scf_model == 1
        % jacket sized by the surrogate in the scan: correct it on this
        % design with the FE (docs/DIMENSIONAMENTO_JACKET.md, section 7)
        ref_answer = strtrim(input(['The FE criteria are not satisfied. Re-size the jacket of this design ' ...
            'with the FE (1-2 more FE runs)? [y/N]: '], 's'));
        if strcmpi(ref_answer, 'y')
            refined = refine_jacket_fe(DATA(sel_idx,:), p);
            if refined.ok
                fprintf('Refined jacket: JT per layer %s mm, radial build %.1f mm.\n', ...
                    mat2str(refined.row.JT*1e3, 3), 1e3*(refined.row.Ri_ - refined.row.Rk_));
            end
            plot_wp_mech_surrogate(refined.mech, p, sprintf('%s - design #%d - refined jacket', tag, sel_idx));
            save(sprintf('%s_results_%s.mat', tag, run_stamp), 'refined', '-append');   % refined.row: the corrected design
        end
    end
end

%% 6. Optional: downstream 3D geometry and magnetic-field research module
coil3d_answer = strtrim(input('Run the 3D coil step (shape + 3D field, research module)? [y/N]: ', 's'));
if strcmpi(coil3d_answer, 'y')
    try
        tf3d = tf3d_from_design(DATA(sel_idx,:), p);
        if tf3d.options.export
            tf3d_dir = fullfile(pwd, sprintf('%s_tf3d_%s', tag, run_stamp));
            tf3d_numeric_files = export_tf3d_results(tf3d, tf3d_dir, sprintf('%s_%d', tag, sel_idx));
            try
                tf3d_files = export_tf3d_shape(tf3d, tf3d_dir, sprintf('%s_%d', tag, sel_idx));
                fprintf('3D exports saved in %s\n', tf3d_dir);
            catch err
                warning('main_WP_TF_design:tf3d_export', '3D export failed: %s', err.message);
            end
        end
        tf3d_figs = plot_tf3d(tf3d, p);
    catch err
        warning('main_WP_TF_design:tf3d', '3D stage failed (calculation, export or plotting): %s', err.message);
    end
end

%% 6b. Optional: 3D beam + shell global model of the TF system, coupled sizing
% The global model (MATLAB counterpart of ANSYS STR_360) is built from the
% chosen design: current centroid line, Lorentz forces of all coils, beam
% section of case + jackets, vault shells. It gives the vertical force that
% the inner leg really carries; the 2D sizing used the bending-free T_bf
% times axial_load_factor. If they differ, the design is sized again with
% the global force and the loop is iterated to convergence
% (COUPLE_GLOBAL_SIZING; docs/MODELLO_GLOBALE_3D.md).
sel_row = DATA(sel_idx,:); p_sel = p;     % design and input used by the steps below
glob_answer = strtrim(input('Run the 3D beam + shell global model of the TF system on this design (about a minute)? [y/N]: ', 's'));
if strcmpi(glob_answer, 'y')
    try
        gm = tf3d_global_from_design(sel_row, p);
        glob_figs = plot_tf3d_global(gm, sprintf('%s - design #%d', tag, sel_idx));
        save(sprintf('%s_results_%s.mat', tag, run_stamp), 'gm', '-append');
        k_sized = axial_load_factor(p);
        if abs(gm.k_axial - k_sized) > 0.01*k_sized
            fprintf(['The inner leg carries %.3f x T_bf; the design was sized with %.3f x T_bf.\n'], ...
                gm.k_axial, k_sized);
            cpl_answer = strtrim(input(['Size this design again with the global axial force, iterating ' ...
                'sizing and global model to convergence (coupled sizing)? [y/N]: '], 's'));
            if strcmpi(cpl_answer, 'y')
                cpl = couple_global_sizing(sel_row, p, struct('gm', gm, 'cal', field_cal));
                plot_tf3d_global(cpl.gm, sprintf('%s - design #%d - coupled', tag, sel_idx), cpl);
                save(sprintf('%s_results_%s.mat', tag, run_stamp), 'cpl', '-append');   % cpl.row: the coupled design
                if ~cpl.rejected
                    sel_row = cpl.row; p_sel = cpl.p;
                    plot_wp_section(sel_row, p_sel, sprintf('%s - design #%d - coupled sizing', tag, sel_idx));
                    fe_answer = strtrim(input('Verify the coupled design with the 2D FE (with the global axial force)? [y/N]: ', 's'));
                    if strcmpi(fe_answer, 'y')
                        mech_cpl = wp_mech_surrogate(sel_row, p_sel);
                        plot_wp_mech_surrogate(mech_cpl, p_sel, sprintf('%s - design #%d - coupled sizing', tag, sel_idx));
                    end
                end
            end
        end
    catch err
        warning('main_WP_TF_design:global', 'Global model / coupled sizing failed: %s', err.message);
    end
end

%% 7. Optional: export the chosen design point as an ANSYS APDL input file
% (the coupled design and its axial load factor, if step 6b re-sized it)
export_answer = strtrim(input('Export this design point as an ANSYS input file for FEM verification? [y/N]: ', 's'));
if strcmpi(export_answer, 'y')
    export_ansys_input(sel_row, p_sel, pwd, sprintf('%s_%d', tag, sel_idx));
end

%% 8. Optional: save all open run plots, including the surrogate FEM
plot_files = ask_save_plots(findall(0, 'Type', 'figure'), ...
    fullfile(pwd, sprintf('%s_plots_%s', tag, run_stamp)));

fprintf(['\nTo revisit this design point later without re-running the scan:\n' ...
    '  [row, p] = load_design_point(''%s'', %d);\n' ...
    '  plot_wp_section(row, p);\n' ...
    'For a manual "what-if" configuration (no Excel), see\n' ...
    'postprocess/plot_wp_section_manual_example.m.\n'], results_file, sel_idx);
