%% main_WP_CS_design.m
% Generic entry point for the CS (Central Solenoid) winding-pack (WP)
% design-point solver, mirroring MADE-2.0/matlab/main_WP_TF_design.m (TF).
%
% Pipeline:
%   1. Ask for (and let you review) the machine parameter Excel file and
%      the plasma-scenario Ampere-turns file.
%   2. Read them into a parameter struct + MAt bound (io/*.m).
%   3. Derive operating parameters and the turns/layers/Iop search space
%      (physics/compute_operating_params.m, search/generate_combinations.m).
%   4. Scan every turns/layers/Iop combination and keep every design point
%      that satisfies the geometric and Tresca stress checks
%      (search/scan_wp_designs.m).
%   5. Save the full results table, then let you browse every feasible
%      design point and choose one to plot and save: scan scatter
%      (plot_solution.m) and module / full-CS section colored by |B|
%      (plot_cs_section.m).
%
% This is a direct port of CS_opt_VNS.m into the TF-style modular
% pipeline (see the manuale CS artifact for the full analysis and the
% "decisioni aperte" this port carries forward unresolved). It has not
% been run in MATLAB in this environment - validate a few known design
% points against CS_opt_VNS.m before trusting it for new designs.
%
% To design a different machine, do NOT edit this file: copy
% input/WP_CS_input_template.xlsx to a new file, edit its parameters, and
% point this script at it (together with that machine's own scenario
% Ampere-turns file) when asked.

clearvars; close all; clc

this_dir = fileparts(mfilename('fullpath'));
addpath(genpath(this_dir));
addpath(fileparts(this_dir)); % MADE-2.0/matlab/: shared xbr.m, xbz.m, xlm.m (used by TF too)

default_input = fullfile(this_dir, 'input', 'WP_CS_input_template.xlsx');

%% 1. Select and review the machine parameter file
fprintf('Machine parameter file [%s]:\n', default_input);
input_answer = strtrim(input('Press Enter to use it, or type another path: ', 's'));
if isempty(input_answer)
    input_file = default_input;
else
    input_file = input_answer;
end

fprintf(['\nBEFORE RUNNING: open %s and review every parameter\n' ...
    '(especially "Machine geometry", "Design point" and "Materials & allowables") - ' ...
    'this run will use exactly what is saved in that file.\n'], input_file);
proceed = strtrim(input('Type "y" to confirm and run the solver: ', 's'));
if ~strcmpi(proceed, 'y')
    fprintf('Aborted: input not confirmed.\n');
    return
end

%% 1b. Select the plasma-scenario Ampere-turns file
fprintf('\nPlasma-scenario Ampere-turns file (e.g. Baseline_VNS_22_07_2025.xlsx):\n');
scenario_file = strtrim(input('Path: ', 's'));
if isempty(scenario_file) || ~isfile(scenario_file)
    error('main_WP_CS_design:scenario_file_required', ...
        'A valid scenario Ampere-turns file is required (see read_scenario_currents.m).');
end

[~, tag] = fileparts(input_file); % used to tag every output file from this run

%% 2-4. Read input, derive parameters, scan the design space
p = read_machine_input(input_file);
MAt = read_scenario_currents(scenario_file);
g = compute_operating_params(p);
env = generate_combinations(p, g, MAt);

fprintf('\nScanning the design space (this can take a while)...\n');
DATA = scan_wp_designs(p, g, env);

if height(DATA) == 0
    error('main_WP_CS_design:no_feasible_design', ...
        ['No feasible design point found for %s.\n' ...
         'Widen the "Numerical settings" (Iop_min/max, min/max_size_CICC, min/max_B, ...) ' ...
         'or review the machine geometry.'], input_file);
end

%% 5. Save all results, then browse and pick one
results_file = sprintf('%s_results_%s.xlsx', tag, string(datetime('now', 'Format', 'yyyyMMdd_HHmmss')));
writetable(DATA, results_file);
fprintf('\n%d feasible design point(s) saved to %s\n', height(DATA), results_file);

sel_idx = browse_solutions(DATA);
plot_solution(DATA, sel_idx, tag);
plot_cs_section(DATA, sel_idx, tag, p, g);
