%% main_WP_CS_design.m
% Generic entry point for the CS (Central Solenoid) winding-pack (WP)
% design-point solver, mirroring MADE-2.0/matlab/main_WP_TF_design.m (TF).
%
% Pipeline:
%   1. Ask for (and let you review) the machine parameter Excel file; the
%      plasma-scenario Ampere-turns file (Baseline*.xlsx) is looked for in the
%      same folder, which becomes the working folder for all outputs.
%   2. Read them into a parameter struct + MAt bound (io/*.m).
%   3. Derive operating parameters and the turns/layers/Iop search space
%      (physics/compute_operating_params.m, search/generate_combinations.m).
%   4. Scan every turns/layers/Iop combination and keep every design point
%      that satisfies the geometric and Tresca stress checks
%      (search/scan_wp_designs.m).
%   5. Save the full results table, then let you browse every feasible
%      design point and choose one to plot and save: scan scatter
%      (plot_solution.m) and module / full-CS section colored by |B|
%      (plot_cs_section.m).
%   6. Optionally verify the chosen design with the axisymmetric FEM of the
%      whole stack (fem/fem_cs_verify.m; fem_detail_module models one
%      module turn by turn), and export it for the ANSYS model
%      (fem/export_apdl_params.m).
%
% This is a direct port of CS_opt_VNS.m into the TF-style modular
% pipeline (see the manuale CS artifact for the full analysis and the
% "decisioni aperte" this port carries forward unresolved). It has not
% been run in MATLAB in this environment - validate a few known design
% points against CS_opt_VNS.m before trusting it for new designs.
%
% To design a different machine, do NOT edit this file: copy
% input/WP_CS_input_template.xlsx to a new file, edit its parameters, and
% point this script at it (together with that machine's own scenario
% Ampere-turns file) when asked.

clearvars; close all; clc

this_dir = fileparts(mfilename('fullpath'));

% CS folders (without CS/test and its Octave shims) + MADE-2.0/matlab/shared;
% removes the folders of an earlier TF/PFC run (MADE_PATHS)
addpath(fileparts(this_dir)); made_paths('CS');

%% 1. Select the machine parameter file; the scenario file is looked for in the same folder
default_input = fullfile(this_dir, 'input', 'WP_CS_input_template.xlsx');
[input_file, scenario_file, work_dir, units] = cs_select_inputs(default_input);

fprintf(['\nBEFORE RUNNING: open %s and review every parameter\n' ...
    '(especially "Machine geometry", "Design point" and "Materials & allowables") - ' ...
    'this run will use exactly what is saved in that file,\n' ...
    'with the scenario file %s (lengths in %s, Ampere-turns in %s).\n' ...
    'The parameter workbook is always in SI as labeled in its Unit column (m, A, V, T, MPa ...).\n'], ...
    input_file, scenario_file, units.len_name, units.cur_name);
proceed = strtrim(input('Type "y" to confirm and run the solver: ', 's'));
if ~strcmpi(proceed, 'y')
    fprintf('Aborted: input not confirmed.\n');
    return
end

% start from the input folder: results, plots and exports are saved there
cd(work_dir);
fprintf('Working folder: %s\n', work_dir);

[~, tag] = fileparts(input_file); % used to tag every output file from this run

%% 2-4. Read input, derive parameters, scan the design space
p = read_machine_input(input_file);
if p.Re_0 > 5 || p.WP_h0 > 5 || p.Iop_max < 1e3
    warning('main_WP_CS_design:units', ...
        'Re_0 = %g, WP_h0 = %g, Iop_max = %g: the workbook expects m and A (not mm / kA). Check the values.', p.Re_0, p.WP_h0, p.Iop_max);
end
MAt = read_scenario_currents(scenario_file, units);
g = compute_operating_params(p);
env = generate_combinations(p, g, MAt);

fprintf('\nScanning the design space (this can take a while)...\n');
DATA = scan_wp_designs(p, g, env);

if height(DATA) == 0
    error('main_WP_CS_design:no_feasible_design', ...
        ['No feasible design point found for %s.\n' ...
         'Widen the "Numerical settings" (Iop_min/max, min/max_size_CICC, min/max_B, ...) ' ...
         'or review the machine geometry.'], input_file);
end

%% 5. Save all results, then browse and pick one
results_file = sprintf('%s_results_%s.xlsx', tag, string(datetime('now', 'Format', 'yyyyMMdd_HHmmss')));
writetable(DATA, results_file);
fprintf('\n%d feasible design point(s) saved to %s\n', height(DATA), results_file);

sel_idx = browse_solutions(DATA);
plot_solution(DATA, sel_idx, tag);
plot_cs_section(DATA, sel_idx, tag, p, g);

%% 6. Optional FEM verification of the chosen design (whole stack, axisymmetric)
if strcmpi(strtrim(input('Verify the chosen design with the FEM stack model? [y/N]: ', 's')), 'y')
    geom = read_coil_geometry(scenario_file, units);
    fem_res = fem_cs_verify(DATA(sel_idx, :), p, g, geom, struct('plot', true));
    save(sprintf('%s_design_%d_fem.mat', tag, sel_idx), 'fem_res');
end
if strcmpi(strtrim(input('Export the design as input for the ANSYS CS model? [y/N]: ', 's')), 'y')
    export_apdl_params(DATA(sel_idx, :), p, g, pwd, sprintf('%s_design_%d', tag, sel_idx));
end
