function out_file = export_ansys_input(row, p, out_dir, template_tag)
%EXPORT_ANSYS_INPUT Write an ANSYS APDL parameter file for a chosen design point.
%
%   out_file = EXPORT_ANSYS_INPUT(row, p, out_dir, template_tag) takes one
%   row of the DATA table produced by SCAN_WP_DESIGNS (e.g. DATA(sel_idx,:)
%   from BROWSE_SOLUTIONS) and the machine parameter struct p (from
%   READ_MACHINE_INPUT), and writes an APDL parameter file that reproduces
%   that exact design point, in the same format as
%   TF_FEM_benchmark_v0_1/patches/changed_files/input/ParametriTF_VNS_LTS_29092025.f
%   (the corrected geometry generator). Drop the resulting file in place of
%   that one (same folder, same name) to re-run the FEM benchmark on the
%   design MATLAB just picked.
%
%   Only the design-defining parameters are derived from row/p (turns,
%   layers, jacket/cable dimensions, current, case radii). A few
%   FEM-only parameters that this 2D solver has no equivalent for
%   (OUTERLEG_INTR, AIR_HEIGHT, and the fixed HOT/WEDGE/SI_UNIT
%   conventions) are left at sensible defaults and flagged with a comment
%   in the output file - review them before running.
%
%   out_dir defaults to pwd; template_tag (default 'design') is used to
%   name the output file.

if nargin < 3 || isempty(out_dir)
    out_dir = pwd;
end
if nargin < 4 || isempty(template_tag)
    template_tag = 'design';
end
if ~isfolder(out_dir)
    mkdir(out_dir);
end

n_layers = row.n_layers;
n_turns = row.n_turns(1:n_layers);
Cond_w  = row.Cond_w(1:n_layers);
Cond_h  = row.Cond_h(1:n_layers);
JT      = row.JT(1:n_layers);

ICIT = p.turn_insulation_nominal*p.Increm;

% LTOT (cell width) must be uniform across layers in this APDL template -
% verify, and warn (do not silently average) if the chosen design breaks
% that assumption.
LTOT = Cond_w(1);
if any(abs(Cond_w - LTOT) > 1e-9)
    warning('export_ansys_input:non_uniform_LTOT', ...
        ['Cond_w is not uniform across layers (range %.6g to %.6g m); ' ...
         'this APDL template assumes a single LTOT. Using layer 1''s value; ' ...
         'review the generated file before running.'], min(Cond_w), max(Cond_w));
end

% Group consecutive layers with identical (n_turns, Cond_h, JT) into
% APDL "grades" (NT/NL/JHG/JT_wG arrays): FEM's GRADES is defined by rows
% sharing the same turn count and cell dimensions, which need not line up
% one-to-one with this solver's cable-type grades (jump_grade) if the
% turn-shrink/extra-layer logic made some rows within one cable type
% differ from their neighbors.
grade_NT = [];
grade_NL = [];
grade_JHG = [];
grade_JTwG = [];
k = 1;
while k <= n_layers
    run_end = k;
    while run_end < n_layers && n_turns(run_end+1) == n_turns(k) ...
            && abs(Cond_h(run_end+1)-Cond_h(k)) < 1e-9 && abs(JT(run_end+1)-JT(k)) < 1e-9
        run_end = run_end + 1;
    end
    grade_NT(end+1) = n_turns(k); %#ok<AGROW>
    grade_NL(end+1) = run_end - k + 1; %#ok<AGROW>
    grade_JHG(end+1) = Cond_h(k); %#ok<AGROW> % raw cell height; APDL subtracts 2*ICIT itself
    grade_JTwG(end+1) = JT(k); %#ok<AGROW>
    k = run_end + 1;
end
n_grades_fem = numel(grade_NT);

if p.shape_cable == 200
    cable_type_str = 'RIS';
else
    cable_type_str = 'rect';
end

CFR = min(max(max(JT), p.r_SC_min), p.r_SC_max);

tag = matlab.lang.makeValidName(template_tag);
out_file = fullfile(out_dir, sprintf('ParametriTF_%s.f', tag));

fid = fopen(out_file, 'w');
if fid < 0
    error('export_ansys_input:cannot_write', 'Could not open %s for writing.', out_file);
end
c = onCleanup(@() fclose(fid));

fprintf(fid, '!-----------------------------------------------------------------------!\n');
fprintf(fid, '! Auto-generated by export_ansys_input.m from MATLAB design point "%s"\n', template_tag);
fprintf(fid, '! Source: search/scan_wp_designs.m DATA row, n_layers=%d, Iop=%.1f A\n', n_layers, row.Iop);
fprintf(fid, '! Review OUTERLEG_INTR and AIR_HEIGHT below: this 2D nose solver has no\n');
fprintf(fid, '! equivalent quantity for them, they are left at template defaults.\n');
fprintf(fid, '!-----------------------------------------------------------------------!\n');
fprintf(fid, '/PREP7\n');
fprintf(fid, 'SCALEV = 1.0\nSCALEE = 1.0\nSCALED = 1.0\n\n');
fprintf(fid, 'SI_UNIT = 1\t\t\t  ! set = 1 to use SI units [ 1 = m -- 0 = mm]\n');
fprintf(fid, '*IF,SI_UNIT,EQ,0,THEN\n\tSCALEV = 1E3\n\tSCALEE = 1E-6\n\tSCALED = 1E-9\n*ENDIF\n\n');
fprintf(fid, 'WEDGE = 1   \t\t\t  ! set =1 to draw 2 half-WP sections and model wedge contact, =0 to draw one half-WP section only\n');
fprintf(fid, 'DEV = -0.0*1.E-3**SI_UNIT ! Jacket external radius deviation from the nominal value\n');
fprintf(fid, 'pi = acos(-1)\n\n');
fprintf(fid, 'HOT = 0                     ! [0 = 4.5 K - 1 = 293 K]\n');
fprintf(fid, 'SCALEF = 1.0\t\n');
fprintf(fid, 'DELTA_SS = 10.38E-6*(293-4) ! 316LN\n');
fprintf(fid, '*IF,HOT,EQ,1,THEN\n\tSCALEF = 1.0+10.38E-6*(293-4)\n*ENDIF\n');
fprintf(fid, '!-----------------------------------------------------------------------!\n');
fprintf(fid, 'N_TF = %d \t\t\t\t! number of TF magnets\n', p.n_TF);
fprintf(fid, 'ANG_DIV = 360/N_TF \t\t! angular separation of TF magnets\n');
fprintf(fid, 'AIR_HEIGHT = 2.0*(2670.00*1.E-3**SI_UNIT)\t! FEM-only, not derived from MATLAB - review\n');
fprintf(fid, '!-----------------------------------------------------------------------!\n');
fprintf(fid, 'SL_LENGTH = 1 ! invariante se non applico momenti al gps\n');
fprintf(fid, '!-----------------------------------------------------------------------!\n');
fprintf(fid, 'WP_TOPOLOGY = ''standard''\n\n');
fprintf(fid, 'GRADES = %d\n\n', n_grades_fem);
fprintf(fid, '*DIM,NT,ARRAY,GRADES,1\n');
for i = 1:n_grades_fem
    fprintf(fid, 'NT(%d,1)  =  %d\n', i, grade_NT(i));
end
fprintf(fid, '\n*DIM,NL,ARRAY,GRADES,1\n');
for i = 1:n_grades_fem
    fprintf(fid, 'NL(%d,1)  =  %d\n', i, grade_NL(i));
end
fprintf(fid, '\n*VOPER,NSPR,NL,MULT,NT\n*VSCFUN,N_WIRES,SUM,NSPR\n\n*VSCFUN,NL_TOT,SUM,NL\n\n');
fprintf(fid, 'DLR = 5.0                 ! number of double - layers ---- DPC if double-pancakes\nDPC = DLR\n\n');
fprintf(fid, '*DIM,LAYOUT,CHAR,3\nLAYOUT(1) = ''DP''\nLAYOUT(2) = ''DL''\nLAYOUT(3) = ''LW''\t\t! Layer Wound\n\n');
fprintf(fid, 'DESIGN = LAYOUT(3)\n\n');
fprintf(fid, 'ICIT = SCALEF*%.6g*1.E-3**SI_UNIT    !Inter Conductor Insulation Thickness\n', ICIT*1e3);
fprintf(fid, 'GIT = SCALEF*%.6g*1.E-3**SI_UNIT     !Ground insulation thickness\n', p.GoundIns*1e3);
fprintf(fid, 'CASE_GIT = SCALEF*0.0*1.E-3**SI_UNIT\n\n');
fprintf(fid, 'BUFF = SCALEF*0.0*1.E-3**SI_UNIT\t\t\t! Insertion gap\nINTLT = SCALEF*0.0*1.E-3**SI_UNIT\n\n');
fprintf(fid, 'WP_GIT = SCALEF*%.6g*1.E-3**SI_UNIT\n', p.GoundIns*1e3);
fprintf(fid, 'DPIT = SCALEF*0\nDLIT = DPIT\t\t\t\t\t\t\t!Double layers insulation thickness\n');
fprintf(fid, 'LWIT = SCALEF*%.6g*1.E-3**SI_UNIT\t!Layer wound insulation thickness\n', p.INS_grades*1e3);
fprintf(fid, 'CFR = SCALEF*%.6g*1.E-3**SI_UNIT       !Cable Fillet Radius = jacket internal radius\n\n', CFR*1e3);
fprintf(fid, 'TF_CURRENT = %.1f\n\n', -row.Iop);
fprintf(fid, '!-----------------------------------------------------------------------!\n!!! ARRAY DEFINITION\n!-----------------------------------------------------------------------!\n');
fprintf(fid, 'NT_G = NT(1)\n*VSCFUN,NL_G,SUM,NL\n\n');
dims = {'CSYS_CABLE','JT_h','JT_w','JH','JW','DPTH','HCH','HCW','HCL','HJH','HJW','JIR','JER','LHI','LWI','R','dJR','GIR'};
for d = 1:numel(dims)
    fprintf(fid, '*DIM,%s,ARRAY,NL_G,NT_G\n', dims{d});
end
fprintf(fid, '*DIM,CABLE_TYPE,CHAR,GRADES,1\n*DIM,JHG,ARRAY, GRADES,1\n*DIM,JT_hG,ARRAY, GRADES,1\n*DIM,JT_wG,ARRAY, GRADES,1\n');
fprintf(fid, '!-----------------------------------------------------------------------!\n!!! Parameters\n!-----------------------------------------------------------------------!\n');
fprintf(fid, '!!! Cable Type\n');
for i = 1:n_grades_fem
    fprintf(fid, 'CABLE_TYPE(%d,1)  = ''%s''\n', i, cable_type_str);
end
fprintf(fid, '\n!!! Conductor Width (Insulated)\nLTOT = SCALEF*(%.6g)*1.E-3**SI_UNIT\n\n', LTOT*1e3);
fprintf(fid, '!!! Non insulated cable Height LOOK -ICIT*2 [m]\n');
for i = 1:n_grades_fem
    fprintf(fid, 'JHG(%d,1) = SCALEF*(%.6g)*1.E-3**SI_UNIT-ICIT*2\n', i, grade_JHG(i)*1e3);
end
fprintf(fid, ['\nn=0\n*DO,i,1,GRADES\n\t*DO,j,1,NL(i)\n\tn=n+1\n\t\t*DO,k,1,NT(i)\n\t\t\t' ...
    'JH(n,k) = JHG(i,1)\n\t\t*ENDDO\n\t*ENDDO\n*ENDDO\n']);
fprintf(fid, '!-----------------------------------------------------------------------!\n!!! Jacket Thickness [m]\n');
for i = 1:n_grades_fem
    fprintf(fid, 'JT_wG(%d,1)    = SCALEF*(%.6g)*1.E-3**SI_UNIT\n', i, grade_JTwG(i)*1e3);
end
for i = 1:n_grades_fem
    fprintf(fid, 'JT_hG(%d,1)   = JT_wG(%d,1)\n', i, i);
end
fprintf(fid, ['!-----------------------------------------------------------------------!\n' ...
    'n=0\n*DO,i,1,GRADES\n\t*DO,j,1,NL(i)\n\t\tn=n+1\n\t\t*DO,k,1,NT(i)\n\t\t\t' ...
    'JT_h(n,k)= JT_hG(i,1)\n\t\t\tJT_w(n,k)= JT_wG(i,1)\n\t\t*ENDDO\n\t*ENDDO\n*ENDDO\n']);
fprintf(fid, ['!-----------------------------------------------------------------------!\n' ...
    '*DIM,H_GRADES,ARRAY,GRADES,1\n*DO,i,1,GRADES\n\tH_GRADES(i)=(JHG(i,1)+2*ICIT)*NL(i)\n*ENDDO\n' ...
    '*VSCFUN,WPH,SUM,H_GRADES\n' ...
    'WPH = WPH+(NL_TOT-1)*LWIT+2*GIT+2*BUFF  \t\t!WP HEIGHT\n\n' ...
    'WPW_HIGHF = LTOT*NT(1)+2*DLIT\nWPW_LOWF = LTOT*NT(GRADES)+2*DLIT\n\n' ...
    '*DIM,W_GRADES,ARRAY,GRADES,1\n*DO,i,1,GRADES\n\tW_GRADES(i)=LTOT*NT(i)\n*ENDDO\n\n' ...
    '!!! GROUND INSULATION PARAMETERS\n' ...
    'INCL = ANG_DIV/2\nRAD1 = LTOT*0.8-BUFF-GIT-DLIT     ! Radius of the DL insulation corner\n' ...
    '!-----------------------------------------------------------------------!\t\n' ...
    '!!! CASE DIMENSION \n']);
fprintf(fid, 'CASE_THICK = SCALEF*%.6g*1.E-3**SI_UNIT\n', p.dr_plasma_side*1e3);
fprintf(fid, 'Ri_ = SCALEF*(%.6g*1e3)*1.E-3**SI_UNIT\n', row.Ri_);
fprintf(fid, 'Rj_ = Ri_-CASE_THICK-WPH\n');
fprintf(fid, 'Rk_ = SCALEF*(%.6g*1e3)*1.E-3**SI_UNIT\n\n', row.Rk_);
fprintf(fid, ['INNLEG_INTR = Rk_\nINNLEG_OUTR = Ri_\nRm_INNERLEG = (INNLEG_INTR+INNLEG_OUTR)/2\n\n']);
fprintf(fid, 'OUTERLEG_INTR = SCALEF*(4.8*1e3)*1.E-3**SI_UNIT\t! FEM-only, not derived from MATLAB - review\n');
fprintf(fid, ['OUTERLEG_OUTR = OUTERLEG_INTR+WPH\nRm_OUTERLEG = (OUTERLEG_INTR+OUTERLEG_OUTR)/2\n\n']);
fprintf(fid, 'CASE_INS = SCALEF*%.6g*1.E-3**SI_UNIT\n\n', 1.5); % wedge-side insulation, template default (not a p.* input yet)
fprintf(fid, ['*AFUN,DEG \n\tCASEW_UP = Ri_*TAN(INCL)*2\n\tCASEW_LOW = Rk_*TAN(INCL)*2\n\n' ...
    '\tCASE_WIDTH = CASEW_UP-2*CASE_INS \n\tCASE_WIDTH_LOW = CASEW_LOW-2*CASE_INS \n\n' ...
    '\tCASE_HEIGHT = Ri_-Rk_\n\n' ...
    '\tWEDGE_OUTR = sqrt(Ri_**2+(CASE_WIDTH/2)**2)\n\tWEDGE_INTR = sqrt(Rk_**2+(CASE_WIDTH_LOW/2)**2)\n\n' ...
    '\tWEDGE_OUTR_INS = sqrt(Ri_**2+(CASEW_UP/2)**2)\n\tWEDGE_INTR_INS = sqrt(Rk_**2+(CASEW_LOW/2)**2)\n' ...
    '*AFUN,RAD \n\n' ...
    'ANG_OUTR = INCL\nPLASMA_FACE_FLAT_WIDTH = CASE_WIDTH\nSTRAIGHT_CASE_HEIGHT = SCALEF*0.0*1.E-3**SI_UNIT\n' ...
    'PLASMA_FACE_EDGE_Y = WEDGE_OUTR*cos(ANG_DIV/2*pi/180)+STRAIGHT_CASE_HEIGHT\n' ...
    'CASE_FLAT = SCALEF*1-20.0*1.E-3**SI_UNIT/CASE_THICK\n' ...
    'NOSE = Rj_-Rk_  \nARC_NOSE = SCALEF*0\n\n' ...
    'WP_INTR = INNLEG_INTR+NOSE\n\n' ...
    'ZOFFST = 0.0\nREF_CS = 0\nREF_CS_SYMM = 0\nSYMM_PLANE = 0\n\n' ...
    'ULT_KP = 0\nULT_LN = 0 \nULT_AREA = 0\n\n']);

% Fixed material/element-type ID mapping - unrelated to the design point,
% copied verbatim from the corrected template.
fprintf(fid, ['!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\nCAB_MAT     = 1\nCAB_ET      = 1\nCAB_ET_3D   = 101\n' ...
    'JCK_MAT     = 2\nJCK_ET      = 2\nJCK_ET_3D   = 102\nTINS_MAT    = 3\nTINS_ET     = 3\nTINS_ET_3D  = 103\n' ...
    'FILL_MAT    = 4\nFILL_ET     = 4\nFILL_ET_3D  = 104\nDPINS_MAT   = 5\nDPINS_ET    = 5\nDPINS_ET_3D = 105\n' ...
    'GINS_MAT_VT = 7\nGINS_MAT_HZ = 8\nGINS_ET     = 7\nGINS_ET_3D  = 107\nBUFF_MAT_VT = 7\nBUFF_MAT_HZ = 8\n' ...
    'BUFF_ET     = 8\nBUFF_ET_3D  = 108\nWINS_MAT    = 9\nWINS_ET     = 9\nWINS_ET_3D  = 109\n' ...
    'CASE_MAT_INN    = 10\nCASE_ET_INN     = 10\nCASE_ET_INN_3D  = 110\nSBP_MAT     = 11\nSBP_ET      = 11\n' ...
    'SBP_ET_3D   = 111\nCASE_MAT_OUT    = 12\nCASE_ET_OUT     = 12\nCASE_ET_OUT_3D  = 112\nOIS_MAT     = 13\n' ...
    'OIS_ET      = 13\nOIS_ET_3D   = 113\nPF_MAT     = 14\nPF_ET      = 14\nPF_ET_3D   = 114\nSPB_MAT     = 15\n' ...
    'SPB_ET      = 15\nSPB_ET_3D   = 115\nSPACER_MAT     = 16\nSPACER_ET      = 16\nSPACER_ET_3D   = 116\n' ...
    'IISINS_MAT    = 17\nIISINS_ET     = 17\nIISINS_ET_3D  = 117\nPLATE1_MAT    = 18\nPLATE1_ET     = 18\n' ...
    'PLATE1_ET_3D  = 118\nPLATE2_MAT    = 19\nPLATE2_ET     = 19\nPLATE2_ET_3D  = 119\nAIR_MAT     = 20\n' ...
    'AIR_ET      = 20\nAIR_ET_3D   = 120\nPF_PLATE_MAT     = 21\nPF_PLATE_ET      = 21\nPF_PLATE_ET_3D   = 121\n' ...
    'PF_TOP_MAT     = 22\nPF_TOP_ET      = 22\nPF_TOP_ET_3D   = 122\nCS_SUP_MAT     = 23\nCS_SUP_ET      = 23\n' ...
    'CS_SUP_ET_3D   = 123\nOMO_MAT     = 30\nOMO_ET \t    = 30\nOMO_ET_3D   = 130\nPF_ET = 31\nPF_ET_3D = 131\n' ...
    'PF_COIL_MAT = 300\nCS_ET = 32\nCS_ET_3D = 132\nCS_MODULES_MAT = 200\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n']);

fprintf('ANSYS input written: %s (%d FEM grade(s) detected from %d layers)\n', out_file, n_grades_fem, n_layers);
end
